SHELL := /bin/bash
.SHELLFLAGS := -e -o pipefail -c
MAKEFLAGS += --no-builtin-rules

BFASST_ROOT := $(realpath .)
BFASST_EXTERNAL_TOOLS := $(BFASST_ROOT)/third_party
BFASST_SETUP := $(BFASST_ROOT)/setup
VENV_VARS := $(BFASST_ROOT)/bfasst.env
GENERAL_VARS := $(BFASST_SETUP)/general.env
PYTHON := $(or $(shell command -v python3.12), $(shell command -v python3.11), python3.10)
VENV_DIR := $(BFASST_ROOT)/.venv
VENV_BIN := $(VENV_DIR)/bin
VENV_ACTIVATE := $(VENV_BIN)/activate

export BASH_ENV=$(VENV_ACTIVATE)

include $(BFASST_SETUP)/external_tools.mk
	
################################### Installation and Setup #########################################
.DEFAULT_GOAL: install
.PHONY: install bare_bones venv init_venv python_packages setup_autocomplete env_vars enable_pre_commit_hook
install: bare_bones all_submodules install_rapidwright install_fasm2bels install_yosys install_wafove
bare_bones: venv setup_autocomplete

init_venv: $(VENV_ACTIVATE)
$(VENV_ACTIVATE) $(VENV_BIN):
	$(PYTHON) -m venv $(VENV_DIR) --prompt bfasst

python_packages: install_cmake pyproject.toml
	python -m pip install -U pip
	python -m pip install -e .

env_vars: $(VENV_VARS)
$(VENV_VARS): $(VENV_ACTIVATE)
	echo "# BFASST Project Environment Variables Pre-generated by Makefile" > $(VENV_VARS)
	echo "# Changes to this file will NOT persist across a fresh install. Change $(GENERAL_VARS) for persistence." >> $(VENV_VARS)
	echo "# Vars are exported with . .venv/bin/activate, reverted to previous values or unset with deactivate" >> $(VENV_VARS)
	echo 'BFASST_ROOT=$(BFASST_ROOT)' >> $(VENV_VARS)
	echo 'BFASST_EXTERNAL_TOOLS=$(BFASST_EXTERNAL_TOOLS)' >> $(VENV_VARS)
	cat $(GENERAL_VARS) >>	$(VENV_VARS)
	echo 'BFASST_ENV_VARS=$(VENV_VARS)' > $(VENV_ACTIVATE).tmp
	echo 'source $(BFASST_SETUP)/env_vars.sh' >>	$(VENV_ACTIVATE).tmp
	sed 's/^deactivate () {/deactivate () {\n    _restore_project_env_vars "$${1:-}"/' $(VENV_ACTIVATE) >>	$(VENV_ACTIVATE).tmp
	echo -e '\n_load_project_env_vars "$(VENV_VARS)"' >>	$(VENV_ACTIVATE).tmp
	mv $(VENV_ACTIVATE).tmp $(VENV_ACTIVATE)
#	touch the venv vars so that it's timestamp metadata is newer than the activate script
	touch $(VENV_VARS)

venv: init_venv python_packages env_vars

AUTO_COMPLETE := source $(BFASST_SETUP)/flow_autocomplete.sh
setup_autocomplete: $(VENV_ACTIVATE)
ifeq ($(shell grep -Fx "$(AUTO_COMPLETE)" "$(VENV_ACTIVATE)"),)
	echo -e "\n$(AUTO_COMPLETE)" >> "$(VENV_ACTIVATE)"
endif

PRE_COMMIT_HOOK = "$(BFASST_ROOT)/.git/hooks/pre-commit"
enable_pre_commit_hook: $(PRE_COMMIT_HOOK)
$(PRE_COMMIT_HOOK):
	echo "#!/bin/bash" > $(PRE_COMMIT_HOOK)
	echo "make pre_commit" >> $(PRE_COMMIT_HOOK)
	chmod +x $(PRE_COMMIT_HOOK)
	@echo "Enabled pre-commit hook at $(PRE_COMMIT_HOOK)"

################################## Linting and Testing #############################################
.PHONY: pre_commit format pylint doctest unittest unittest_failfast
pre_commit: doctest pylint

format:
	find ./scripts ./bfasst -iname "*.py" -exec black -q -l 100 {} \;

pylint: format
	git fetch origin main
	pylint --errors-only $$(git ls-files --directory scripts --directory bfasst | grep -e ".py$$")
	pylint $$(git diff origin/main --diff-filter=AM --name-only | grep -e ".py$$")

doctest:
	find bfasst -iname "*.py" -exec python -m doctest {} \;

unittest:
	python -m unittest

unittest_failfast:
	python -m unittest -f
