// ==============================================================
// RTL generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2011.1
// Copyright (C) 2011 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fetch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        tag,
        counter,
        a_address0,
        a_ce0,
        a_we0,
        a_d0,
        a_address1,
        a_ce1,
        a_we1,
        a_d1,
        V_bus_req_din,
        V_bus_req_full_n,
        V_bus_req_write,
        V_bus_rsp_dout,
        V_bus_rsp_empty_n,
        V_bus_rsp_read,
        V_bus_address,
        V_bus_datain,
        V_bus_dataout,
        V_bus_size
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
input  [1:0] tag;
input  [6:0] counter;
output  [11:0] a_address0;
output   a_ce0;
output   a_we0;
output  [31:0] a_d0;
output  [11:0] a_address1;
output   a_ce1;
output   a_we1;
output  [31:0] a_d1;
output   V_bus_req_din;
input   V_bus_req_full_n;
output   V_bus_req_write;
input   V_bus_rsp_dout;
input   V_bus_rsp_empty_n;
output   V_bus_rsp_read;
output  [31:0] V_bus_address;
input  [127:0] V_bus_datain;
output  [127:0] V_bus_dataout;
output  [31:0] V_bus_size;

reg ap_done;
reg ap_idle;
reg[11:0] a_address0;
reg a_ce0;
reg a_we0;
reg[31:0] a_d0;
reg[11:0] a_address1;
reg a_ce1;
reg a_we1;
reg[31:0] a_d1;
reg V_bus_req_write;
reg V_bus_rsp_read;
reg[31:0] V_bus_address;
reg   [2:0] ap_CS_fsm;
reg   [10:0] indvar_flatten_reg_180;
reg   [6:0] i_reg_191;
reg   [4:0] indvar1_reg_202;
reg   [6:0] j_reg_213;
reg   [10:0] indvar_flatten1_reg_224;
reg   [6:0] i_1_reg_235;
reg   [4:0] indvar_reg_246;
reg   [6:0] j_1_reg_257;
wire   [19:0] tmp3_cast_fu_303_p1;
reg   [19:0] tmp3_cast_reg_835;
wire   [0:0] icmp_fu_281_p2;
wire   [0:0] tmp_2_fu_287_p2;
wire   [19:0] tmp2_fu_321_p2;
reg   [19:0] tmp2_reg_840;
wire   [0:0] exitcond2_fu_327_p2;
reg   [0:0] exitcond2_reg_845;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_sig_bdd_86;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond2_reg_845_pp0_it1;
reg   [10:0] indvar_flatten_next_reg_849;
reg   [6:0] j_mid2_reg_854;
reg   [6:0] ap_reg_ppstg_j_mid2_reg_854_pp0_it1;
wire   [6:0] i_mid2_fu_367_p3;
reg   [6:0] i_mid2_reg_863;
reg   [6:0] ap_reg_ppstg_i_mid2_reg_863_pp0_it1;
wire   [19:0] tmp13_fu_409_p2;
reg   [19:0] tmp13_reg_869;
reg   [4:0] indvar_next1_reg_874;
reg    ap_sig_bdd_119;
reg   [31:0] tmp_17_reg_884;
reg   [31:0] p_4_reg_889;
reg   [31:0] p_5_reg_894;
reg   [31:0] p_6_reg_899;
wire   [6:0] tmp_25_fu_470_p2;
wire   [13:0] a_addr2_cast_fu_491_p1;
reg   [13:0] a_addr2_cast_reg_909;
wire   [0:0] exitcond_fu_576_p2;
reg   [0:0] exitcond_reg_915;
reg    ap_reg_ppiten_pp1_it0;
reg    ap_sig_bdd_151;
reg    ap_reg_ppiten_pp1_it1;
reg    ap_reg_ppiten_pp1_it2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_915_pp1_it1;
reg   [10:0] indvar_flatten_next1_reg_919;
reg   [6:0] j_1_mid2_reg_924;
reg   [6:0] ap_reg_ppstg_j_1_mid2_reg_924_pp1_it1;
wire   [6:0] i_1_mid2_fu_616_p3;
reg   [6:0] i_1_mid2_reg_933;
reg   [6:0] ap_reg_ppstg_i_1_mid2_reg_933_pp1_it1;
reg   [17:0] tmp_26_reg_939;
reg   [4:0] indvar_next_reg_944;
reg    ap_sig_bdd_183;
reg   [31:0] tmp_9_reg_954;
reg   [31:0] p_1_reg_959;
reg   [31:0] p_2_reg_964;
reg   [31:0] p_3_reg_969;
wire   [6:0] tmp_13_fu_723_p2;
wire   [13:0] a_addr9_cast_fu_744_p1;
reg   [13:0] a_addr9_cast_reg_979;
reg   [10:0] indvar_flatten_phi_fu_184_p4;
reg   [6:0] i_phi_fu_195_p4;
reg   [4:0] indvar1_phi_fu_206_p4;
reg   [6:0] j_phi_fu_217_p4;
reg   [10:0] indvar_flatten1_phi_fu_228_p4;
reg   [6:0] i_1_phi_fu_239_p4;
reg   [4:0] indvar_phi_fu_250_p4;
reg   [6:0] j_1_phi_fu_261_p4;
wire   [63:0] tmp_18_fu_501_p1;
wire   [63:0] tmp_20_fu_525_p1;
wire   [63:0] tmp_22_fu_548_p1;
wire   [63:0] tmp_24_fu_571_p1;
wire   [63:0] tmp_3_fu_754_p1;
wire   [63:0] tmp_4_fu_778_p1;
wire   [63:0] tmp_10_fu_801_p1;
wire   [63:0] tmp_12_fu_824_p1;
wire   [63:0] tmp_16_fu_425_p1;
wire   [63:0] tmp_7_fu_679_p1;
wire   [31:0] tmp18_fu_475_p1;
wire   [31:0] tmp12_fu_535_p1;
wire   [31:0] tmp15_fu_728_p1;
wire   [31:0] tmp14_fu_788_p1;
wire   [31:0] tmp16_fu_511_p1;
wire   [31:0] tmp8_fu_558_p1;
wire   [31:0] tmp17_fu_764_p1;
wire   [31:0] tmp10_fu_811_p1;
wire   [0:0] tmp_1_fu_269_p3;
wire   [1:0] tmp_8_fu_277_p1;
wire   [18:0] counter_cast_fu_293_p1;
wire   [18:0] tmp3_fu_297_p2;
wire   [18:0] counter_cast2_fu_307_p1;
wire   [18:0] tmp1_fu_311_p2;
wire   [19:0] tmp1_cast_fu_317_p1;
wire   [0:0] exitcond3_fu_339_p2;
wire   [6:0] tmp_17_dup_fu_361_p2;
wire   [12:0] i_cast_fu_375_p1;
wire   [4:0] indvar1_mid2_fu_345_p3;
wire   [6:0] indvar1_cast_fu_385_p1;
wire   [6:0] tmp7_fu_389_p2;
wire   [12:0] tmp6_fu_379_p2;
wire   [12:0] tmp7_cast_fu_395_p1;
wire   [12:0] tmp11_fu_399_p2;
wire   [19:0] tmp11_cast_fu_405_p1;
wire   [19:0] tmp_15_fu_420_p2;
wire   [12:0] tmp_4_trn_cast_fu_479_p1;
wire   [12:0] a_addr2_fu_485_p2;
wire   [13:0] tmp_22_trn_cast_fu_482_p1;
wire   [13:0] a_addr3_fu_495_p2;
wire   [6:0] tmp_19_fu_506_p2;
wire   [13:0] tmp_24_trn_cast_fu_515_p1;
wire   [13:0] a_addr5_fu_519_p2;
wire   [6:0] tmp_21_fu_530_p2;
wire   [13:0] tmp_26_trn_cast_fu_539_p1;
wire   [13:0] a_addr6_fu_543_p2;
wire   [6:0] tmp_23_fu_553_p2;
wire   [13:0] tmp_28_trn_cast_fu_562_p1;
wire   [13:0] a_addr8_fu_566_p2;
wire   [0:0] exitcond1_fu_588_p2;
wire   [6:0] tmp_5_dup_fu_610_p2;
wire   [12:0] i_1_cast_fu_624_p1;
wire   [4:0] indvar_mid2_fu_594_p3;
wire   [6:0] indvar_cast_fu_634_p1;
wire   [6:0] tmp_fu_638_p2;
wire   [12:0] tmp4_fu_628_p2;
wire   [12:0] tmp_cast_fu_644_p1;
wire   [12:0] tmp5_fu_648_p2;
wire   [19:0] tmp5_cast_cast_fu_654_p1;
wire   [19:0] tmp9_fu_658_p2;
wire   [12:0] tmp_3_trn8_cast_fu_732_p1;
wire   [12:0] a_addr9_fu_738_p2;
wire   [13:0] tmp_trn_cast_fu_735_p1;
wire   [13:0] a_addr_fu_748_p2;
wire   [6:0] tmp_s_fu_759_p2;
wire   [13:0] tmp_11_trn_cast_fu_768_p1;
wire   [13:0] a_addr7_fu_772_p2;
wire   [6:0] tmp_5_fu_783_p2;
wire   [13:0] tmp_13_trn_cast_fu_792_p1;
wire   [13:0] a_addr4_fu_796_p2;
wire   [6:0] tmp_11_fu_806_p2;
wire   [13:0] tmp_15_trn_cast_fu_815_p1;
wire   [13:0] a_addr1_fu_819_p2;
reg   [2:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st0_fsm_0 = 3'b000;
parameter    ap_ST_st1_fsm_1 = 3'b001;
parameter    ap_ST_pp0_stg0_fsm_2 = 3'b010;
parameter    ap_ST_pp0_stg1_fsm_3 = 3'b011;
parameter    ap_ST_pp1_stg0_fsm_4 = 3'b100;
parameter    ap_ST_pp1_stg1_fsm_5 = 3'b101;
parameter    ap_ST_st12_fsm_6 = 3'b110;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_6 = 32'b00000000000000000000000000000110;
parameter    ap_const_lv2_1 = 2'b01;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv19_C = 19'b0000000000000001100;
parameter    ap_const_lv20_3F000 = 20'b00111111000000000000;
parameter    ap_const_lv11_400 = 11'b10000000000;
parameter    ap_const_lv11_1 = 11'b00000000001;
parameter    ap_const_lv5_10 = 5'b10000;
parameter    ap_const_lv7_1 = 7'b0000001;
parameter    ap_const_lv13_6 = 13'b0000000000110;
parameter    ap_const_lv7_2 = 7'b0000010;
parameter    ap_const_lv5_1 = 5'b00001;
parameter    ap_const_lv20_2 = 20'b00000000000000000010;
parameter    ap_const_lv32_20 = 32'b00000000000000000000000000100000;
parameter    ap_const_lv32_3F = 32'b00000000000000000000000000111111;
parameter    ap_const_lv32_40 = 32'b00000000000000000000000001000000;
parameter    ap_const_lv32_5F = 32'b00000000000000000000000001011111;
parameter    ap_const_lv32_60 = 32'b00000000000000000000000001100000;
parameter    ap_const_lv32_7F = 32'b00000000000000000000000001111111;
parameter    ap_const_lv7_4 = 7'b0000100;
parameter    ap_const_lv7_3 = 7'b0000011;
parameter    ap_const_lv32_2 = 32'b00000000000000000000000000000010;
parameter    ap_const_lv32_13 = 32'b00000000000000000000000000010011;
parameter    ap_const_lv128_lc_1 = 128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_true = 1'b1;




/// ap_CS_fsm assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_lv1_0 == exitcond2_fu_327_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & (icmp_fu_281_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_287_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_lv1_0 == exitcond2_reg_845) & (ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st1_fsm_1 == ap_CS_fsm) & (icmp_fu_281_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_287_p2)) | ((ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119) & ~(ap_const_lv1_0 == exitcond2_reg_845)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & (icmp_fu_281_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_287_p2))) begin
            ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp1_it0 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~(ap_const_lv1_0 == exitcond_fu_576_p2))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(icmp_fu_281_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp1_it1 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_lv1_0 == exitcond_reg_915) & (ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(icmp_fu_281_p2 == ap_const_lv1_0)) | ((ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183) & ~(ap_const_lv1_0 == exitcond_reg_915)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp1_it2 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183))) begin
            ap_reg_ppiten_pp1_it2 <= ap_reg_ppiten_pp1_it1;
        end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(icmp_fu_281_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it2 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1))) begin
        a_addr2_cast_reg_909[6] <= a_addr2_cast_fu_491_p1[6];
        a_addr2_cast_reg_909[7] <= a_addr2_cast_fu_491_p1[7];
        a_addr2_cast_reg_909[8] <= a_addr2_cast_fu_491_p1[8];
        a_addr2_cast_reg_909[9] <= a_addr2_cast_fu_491_p1[9];
        a_addr2_cast_reg_909[10] <= a_addr2_cast_fu_491_p1[10];
        a_addr2_cast_reg_909[11] <= a_addr2_cast_fu_491_p1[11];
        a_addr2_cast_reg_909[12] <= a_addr2_cast_fu_491_p1[12];
    end
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1))) begin
        a_addr9_cast_reg_979[6] <= a_addr9_cast_fu_744_p1[6];
        a_addr9_cast_reg_979[7] <= a_addr9_cast_fu_744_p1[7];
        a_addr9_cast_reg_979[8] <= a_addr9_cast_fu_744_p1[8];
        a_addr9_cast_reg_979[9] <= a_addr9_cast_fu_744_p1[9];
        a_addr9_cast_reg_979[10] <= a_addr9_cast_fu_744_p1[10];
        a_addr9_cast_reg_979[11] <= a_addr9_cast_fu_744_p1[11];
        a_addr9_cast_reg_979[12] <= a_addr9_cast_fu_744_p1[12];
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        ap_reg_ppstg_exitcond2_reg_845_pp0_it1 <= exitcond2_reg_845;
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        ap_reg_ppstg_exitcond_reg_915_pp1_it1 <= exitcond_reg_915;
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        ap_reg_ppstg_i_1_mid2_reg_933_pp1_it1 <= i_1_mid2_reg_933;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        ap_reg_ppstg_i_mid2_reg_863_pp0_it1 <= i_mid2_reg_863;
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        ap_reg_ppstg_j_1_mid2_reg_924_pp1_it1 <= j_1_mid2_reg_924;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        ap_reg_ppstg_j_mid2_reg_854_pp0_it1 <= j_mid2_reg_854;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        exitcond2_reg_845 <= (indvar_flatten_phi_fu_184_p4 == ap_const_lv11_400? 1'b1: 1'b0);
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        exitcond_reg_915 <= (indvar_flatten1_phi_fu_228_p4 == ap_const_lv11_400? 1'b1: 1'b0);
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == exitcond_fu_576_p2))) begin
        if (exitcond1_fu_588_p2) begin
            i_1_mid2_reg_933 <= tmp_5_dup_fu_610_p2;
        end else begin
            i_1_mid2_reg_933 <= i_1_phi_fu_239_p4;
        end

    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        i_1_reg_235 <= i_1_mid2_reg_933;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(icmp_fu_281_p2 == ap_const_lv1_0))) begin
        i_1_reg_235 <= ap_const_lv7_0;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == exitcond2_fu_327_p2))) begin
        if (exitcond3_fu_339_p2) begin
            i_mid2_reg_863 <= tmp_17_dup_fu_361_p2;
        end else begin
            i_mid2_reg_863 <= i_phi_fu_195_p4;
        end

    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        i_reg_191 <= i_mid2_reg_863;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & (icmp_fu_281_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_287_p2))) begin
        i_reg_191 <= ap_const_lv7_0;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        indvar1_reg_202 <= indvar_next1_reg_874;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & (icmp_fu_281_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_287_p2))) begin
        indvar1_reg_202 <= ap_const_lv5_0;
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        indvar_flatten1_reg_224 <= indvar_flatten_next1_reg_919;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(icmp_fu_281_p2 == ap_const_lv1_0))) begin
        indvar_flatten1_reg_224 <= ap_const_lv11_0;
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        indvar_flatten_next1_reg_919 <= (indvar_flatten1_phi_fu_228_p4 + ap_const_lv11_1);
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        indvar_flatten_next_reg_849 <= (indvar_flatten_phi_fu_184_p4 + ap_const_lv11_1);
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        indvar_flatten_reg_180 <= indvar_flatten_next_reg_849;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & (icmp_fu_281_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_287_p2))) begin
        indvar_flatten_reg_180 <= ap_const_lv11_0;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == exitcond2_fu_327_p2))) begin
        indvar_next1_reg_874 <= (indvar1_mid2_fu_345_p3 + ap_const_lv5_1);
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == exitcond_fu_576_p2))) begin
        indvar_next_reg_944 <= (indvar_mid2_fu_594_p3 + ap_const_lv5_1);
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        indvar_reg_246 <= indvar_next_reg_944;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(icmp_fu_281_p2 == ap_const_lv1_0))) begin
        indvar_reg_246 <= ap_const_lv5_0;
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == exitcond_fu_576_p2))) begin
        if (exitcond1_fu_588_p2) begin
            j_1_mid2_reg_924 <= ap_const_lv7_0;
        end else begin
            j_1_mid2_reg_924 <= j_1_phi_fu_261_p4;
        end

    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        j_1_reg_257 <= (j_1_mid2_reg_924 + ap_const_lv7_4);
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(icmp_fu_281_p2 == ap_const_lv1_0))) begin
        j_1_reg_257 <= ap_const_lv7_0;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == exitcond2_fu_327_p2))) begin
        if (exitcond3_fu_339_p2) begin
            j_mid2_reg_854 <= ap_const_lv7_0;
        end else begin
            j_mid2_reg_854 <= j_phi_fu_217_p4;
        end

    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        j_reg_213 <= (j_mid2_reg_854 + ap_const_lv7_4);
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & (icmp_fu_281_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_287_p2))) begin
        j_reg_213 <= ap_const_lv7_0;
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        p_1_reg_959 <= {{V_bus_datain[ap_const_lv32_3F : ap_const_lv32_20]}};
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        p_2_reg_964 <= {{V_bus_datain[ap_const_lv32_5F : ap_const_lv32_40]}};
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        p_3_reg_969 <= {{V_bus_datain[ap_const_lv32_7F : ap_const_lv32_60]}};
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        p_4_reg_889 <= {{V_bus_datain[ap_const_lv32_3F : ap_const_lv32_20]}};
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        p_5_reg_894 <= {{V_bus_datain[ap_const_lv32_5F : ap_const_lv32_40]}};
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        p_6_reg_899 <= {{V_bus_datain[ap_const_lv32_7F : ap_const_lv32_60]}};
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == exitcond2_fu_327_p2))) begin
        tmp13_reg_869[2] <= tmp13_fu_409_p2[2];
        tmp13_reg_869[3] <= tmp13_fu_409_p2[3];
        tmp13_reg_869[4] <= tmp13_fu_409_p2[4];
        tmp13_reg_869[5] <= tmp13_fu_409_p2[5];
        tmp13_reg_869[6] <= tmp13_fu_409_p2[6];
        tmp13_reg_869[7] <= tmp13_fu_409_p2[7];
        tmp13_reg_869[8] <= tmp13_fu_409_p2[8];
        tmp13_reg_869[9] <= tmp13_fu_409_p2[9];
        tmp13_reg_869[10] <= tmp13_fu_409_p2[10];
        tmp13_reg_869[11] <= tmp13_fu_409_p2[11];
        tmp13_reg_869[12] <= tmp13_fu_409_p2[12];
        tmp13_reg_869[13] <= tmp13_fu_409_p2[13];
        tmp13_reg_869[14] <= tmp13_fu_409_p2[14];
        tmp13_reg_869[15] <= tmp13_fu_409_p2[15];
        tmp13_reg_869[16] <= tmp13_fu_409_p2[16];
        tmp13_reg_869[17] <= tmp13_fu_409_p2[17];
        tmp13_reg_869[18] <= tmp13_fu_409_p2[18];
        tmp13_reg_869[19] <= tmp13_fu_409_p2[19];
    end
    if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(icmp_fu_281_p2 == ap_const_lv1_0))) begin
        tmp2_reg_840[12] <= tmp2_fu_321_p2[12];
        tmp2_reg_840[13] <= tmp2_fu_321_p2[13];
        tmp2_reg_840[14] <= tmp2_fu_321_p2[14];
        tmp2_reg_840[15] <= tmp2_fu_321_p2[15];
        tmp2_reg_840[16] <= tmp2_fu_321_p2[16];
        tmp2_reg_840[17] <= tmp2_fu_321_p2[17];
        tmp2_reg_840[18] <= tmp2_fu_321_p2[18];
        tmp2_reg_840[19] <= tmp2_fu_321_p2[19];
    end
    if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & (icmp_fu_281_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_287_p2))) begin
        tmp3_cast_reg_835[12] <= tmp3_cast_fu_303_p1[12];
        tmp3_cast_reg_835[13] <= tmp3_cast_fu_303_p1[13];
        tmp3_cast_reg_835[14] <= tmp3_cast_fu_303_p1[14];
        tmp3_cast_reg_835[15] <= tmp3_cast_fu_303_p1[15];
        tmp3_cast_reg_835[16] <= tmp3_cast_fu_303_p1[16];
        tmp3_cast_reg_835[17] <= tmp3_cast_fu_303_p1[17];
        tmp3_cast_reg_835[18] <= tmp3_cast_fu_303_p1[18];
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        tmp_17_reg_884 <= V_bus_datain[31:0];
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == exitcond_fu_576_p2))) begin
        tmp_26_reg_939 <= {{tmp9_fu_658_p2[ap_const_lv32_13 : ap_const_lv32_2]}};
    end
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        tmp_9_reg_954 <= V_bus_datain[31:0];
    end
end

/// V_bus_address assign process. ///
always @ (ap_CS_fsm or exitcond2_reg_845 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_119 or exitcond_reg_915 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_183 or tmp_16_fu_425_p1 or tmp_7_fu_679_p1)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183))) begin
        V_bus_address = tmp_7_fu_679_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119))) begin
        V_bus_address = tmp_16_fu_425_p1;
    end else begin
        V_bus_address = tmp_7_fu_679_p1;
    end
end

/// V_bus_req_write assign process. ///
always @ (ap_CS_fsm or exitcond2_reg_845 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_119 or exitcond_reg_915 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_183)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183)))) begin
        V_bus_req_write = ap_const_logic_1;
    end else begin
        V_bus_req_write = ap_const_logic_0;
    end
end

/// V_bus_rsp_read assign process. ///
always @ (ap_CS_fsm or exitcond2_reg_845 or ap_sig_bdd_86 or ap_reg_ppiten_pp0_it1 or exitcond_reg_915 or ap_sig_bdd_151 or ap_reg_ppiten_pp1_it1)
begin
    if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) | ((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        V_bus_rsp_read = ap_const_logic_1;
    end else begin
        V_bus_rsp_read = ap_const_logic_0;
    end
end

/// a_address0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_86 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond2_reg_845_pp0_it1 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_151 or ap_reg_ppiten_pp1_it1 or ap_reg_ppiten_pp1_it2 or ap_reg_ppstg_exitcond_reg_915_pp1_it1 or ap_sig_bdd_183 or tmp_18_fu_501_p1 or tmp_22_fu_548_p1 or tmp_3_fu_754_p1 or tmp_10_fu_801_p1)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1))) begin
        a_address0 = tmp_10_fu_801_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1))) begin
        a_address0 = tmp_3_fu_754_p1;
    end else if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1))) begin
        a_address0 = tmp_22_fu_548_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1))) begin
        a_address0 = tmp_18_fu_501_p1;
    end else begin
        a_address0 = tmp_10_fu_801_p1;
    end
end

/// a_address1 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_86 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond2_reg_845_pp0_it1 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_151 or ap_reg_ppiten_pp1_it1 or ap_reg_ppiten_pp1_it2 or ap_reg_ppstg_exitcond_reg_915_pp1_it1 or ap_sig_bdd_183 or tmp_20_fu_525_p1 or tmp_24_fu_571_p1 or tmp_4_fu_778_p1 or tmp_12_fu_824_p1)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1))) begin
        a_address1 = tmp_12_fu_824_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1))) begin
        a_address1 = tmp_4_fu_778_p1;
    end else if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1))) begin
        a_address1 = tmp_24_fu_571_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1))) begin
        a_address1 = tmp_20_fu_525_p1;
    end else begin
        a_address1 = tmp_12_fu_824_p1;
    end
end

/// a_ce0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_86 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond2_reg_845_pp0_it1 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_151 or ap_reg_ppiten_pp1_it1 or ap_reg_ppiten_pp1_it2 or ap_reg_ppstg_exitcond_reg_915_pp1_it1 or ap_sig_bdd_183)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1)) | ((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1)))) begin
        a_ce0 = ap_const_logic_1;
    end else begin
        a_ce0 = ap_const_logic_0;
    end
end

/// a_ce1 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_86 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond2_reg_845_pp0_it1 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_151 or ap_reg_ppiten_pp1_it1 or ap_reg_ppiten_pp1_it2 or ap_reg_ppstg_exitcond_reg_915_pp1_it1 or ap_sig_bdd_183)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1)) | ((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1)))) begin
        a_ce1 = ap_const_logic_1;
    end else begin
        a_ce1 = ap_const_logic_0;
    end
end

/// a_d0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_86 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond2_reg_845_pp0_it1 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_151 or ap_reg_ppiten_pp1_it1 or ap_reg_ppiten_pp1_it2 or ap_reg_ppstg_exitcond_reg_915_pp1_it1 or ap_sig_bdd_183 or tmp18_fu_475_p1 or tmp12_fu_535_p1 or tmp15_fu_728_p1 or tmp14_fu_788_p1)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1))) begin
        a_d0 = tmp14_fu_788_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1))) begin
        a_d0 = tmp15_fu_728_p1;
    end else if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1))) begin
        a_d0 = tmp12_fu_535_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1))) begin
        a_d0 = tmp18_fu_475_p1;
    end else begin
        a_d0 = tmp14_fu_788_p1;
    end
end

/// a_d1 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_86 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond2_reg_845_pp0_it1 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_151 or ap_reg_ppiten_pp1_it1 or ap_reg_ppiten_pp1_it2 or ap_reg_ppstg_exitcond_reg_915_pp1_it1 or ap_sig_bdd_183 or tmp16_fu_511_p1 or tmp8_fu_558_p1 or tmp17_fu_764_p1 or tmp10_fu_811_p1)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1))) begin
        a_d1 = tmp10_fu_811_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1))) begin
        a_d1 = tmp17_fu_764_p1;
    end else if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1))) begin
        a_d1 = tmp8_fu_558_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1))) begin
        a_d1 = tmp16_fu_511_p1;
    end else begin
        a_d1 = tmp10_fu_811_p1;
    end
end

/// a_we0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_86 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond2_reg_845_pp0_it1 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_151 or ap_reg_ppiten_pp1_it1 or ap_reg_ppiten_pp1_it2 or ap_reg_ppstg_exitcond_reg_915_pp1_it1 or ap_sig_bdd_183)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1)) | ((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1)))) begin
        a_we0 = ap_const_logic_1;
    end else begin
        a_we0 = ap_const_logic_0;
    end
end

/// a_we1 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_86 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond2_reg_845_pp0_it1 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_151 or ap_reg_ppiten_pp1_it1 or ap_reg_ppiten_pp1_it2 or ap_reg_ppstg_exitcond_reg_915_pp1_it1 or ap_sig_bdd_183)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_845_pp0_it1)) | ((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_915_pp1_it1)))) begin
        a_we1 = ap_const_logic_1;
    end else begin
        a_we1 = ap_const_logic_0;
    end
end

/// ap_NS_fsm assign process. ///
always @ (ap_start or ap_CS_fsm or icmp_fu_281_p2 or tmp_2_fu_287_p2 or exitcond2_fu_327_p2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_86 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_119 or exitcond_fu_576_p2 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_151 or ap_reg_ppiten_pp1_it1 or ap_reg_ppiten_pp1_it2 or ap_sig_bdd_183)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~(ap_const_lv1_0 == exitcond_fu_576_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        ap_NS_fsm = ap_ST_pp1_stg1_fsm_5;
    end else if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_lv1_0 == exitcond2_fu_327_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        ap_NS_fsm = ap_ST_pp0_stg1_fsm_3;
    end else if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st12_fsm_6 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st0_fsm_0;
    end else if ((((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(icmp_fu_281_p2 == ap_const_lv1_0)) | ((ap_ST_pp1_stg1_fsm_5 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_183)))) begin
        ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
    end else if ((((ap_ST_st1_fsm_1 == ap_CS_fsm) & (icmp_fu_281_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_fu_287_p2)) | ((ap_ST_pp0_stg1_fsm_3 == ap_CS_fsm) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_119)))) begin
        ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
    end else if ((((ap_ST_st1_fsm_1 == ap_CS_fsm) & (icmp_fu_281_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_2_fu_287_p2)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_86 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_lv1_0 == exitcond2_fu_327_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) | ((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_151 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~(ap_const_lv1_0 == exitcond_fu_576_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        ap_NS_fsm = ap_ST_st12_fsm_6;
    end else if ((((ap_ST_st0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_start)) | ((ap_const_logic_1 == ap_start) & (ap_ST_st12_fsm_6 == ap_CS_fsm)))) begin
        ap_NS_fsm = ap_ST_st1_fsm_1;
    end else begin
        ap_NS_fsm = ap_CS_fsm;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st0_fsm_0 == ap_CS_fsm) | (ap_ST_st12_fsm_6 == ap_CS_fsm))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st0_fsm_0 == ap_CS_fsm)) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// i_1_phi_fu_239_p4 assign process. ///
always @ (ap_CS_fsm or i_1_reg_235 or exitcond_reg_915 or ap_reg_ppiten_pp1_it1 or i_1_mid2_reg_933)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        i_1_phi_fu_239_p4 = i_1_mid2_reg_933;
    end else begin
        i_1_phi_fu_239_p4 = i_1_reg_235;
    end
end

/// i_phi_fu_195_p4 assign process. ///
always @ (ap_CS_fsm or i_reg_191 or exitcond2_reg_845 or ap_reg_ppiten_pp0_it1 or i_mid2_reg_863)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        i_phi_fu_195_p4 = i_mid2_reg_863;
    end else begin
        i_phi_fu_195_p4 = i_reg_191;
    end
end

/// indvar1_phi_fu_206_p4 assign process. ///
always @ (ap_CS_fsm or indvar1_reg_202 or exitcond2_reg_845 or ap_reg_ppiten_pp0_it1 or indvar_next1_reg_874)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        indvar1_phi_fu_206_p4 = indvar_next1_reg_874;
    end else begin
        indvar1_phi_fu_206_p4 = indvar1_reg_202;
    end
end

/// indvar_flatten1_phi_fu_228_p4 assign process. ///
always @ (ap_CS_fsm or indvar_flatten1_reg_224 or exitcond_reg_915 or ap_reg_ppiten_pp1_it1 or indvar_flatten_next1_reg_919)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        indvar_flatten1_phi_fu_228_p4 = indvar_flatten_next1_reg_919;
    end else begin
        indvar_flatten1_phi_fu_228_p4 = indvar_flatten1_reg_224;
    end
end

/// indvar_flatten_phi_fu_184_p4 assign process. ///
always @ (ap_CS_fsm or indvar_flatten_reg_180 or exitcond2_reg_845 or ap_reg_ppiten_pp0_it1 or indvar_flatten_next_reg_849)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        indvar_flatten_phi_fu_184_p4 = indvar_flatten_next_reg_849;
    end else begin
        indvar_flatten_phi_fu_184_p4 = indvar_flatten_reg_180;
    end
end

/// indvar_phi_fu_250_p4 assign process. ///
always @ (ap_CS_fsm or indvar_reg_246 or exitcond_reg_915 or ap_reg_ppiten_pp1_it1 or indvar_next_reg_944)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        indvar_phi_fu_250_p4 = indvar_next_reg_944;
    end else begin
        indvar_phi_fu_250_p4 = indvar_reg_246;
    end
end

/// j_1_phi_fu_261_p4 assign process. ///
always @ (ap_CS_fsm or j_1_reg_257 or exitcond_reg_915 or ap_reg_ppiten_pp1_it1 or tmp_13_fu_723_p2)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_reg_915) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        j_1_phi_fu_261_p4 = tmp_13_fu_723_p2;
    end else begin
        j_1_phi_fu_261_p4 = j_1_reg_257;
    end
end

/// j_phi_fu_217_p4 assign process. ///
always @ (ap_CS_fsm or j_reg_213 or exitcond2_reg_845 or ap_reg_ppiten_pp0_it1 or tmp_25_fu_470_p2)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_reg_845) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        j_phi_fu_217_p4 = tmp_25_fu_470_p2;
    end else begin
        j_phi_fu_217_p4 = j_reg_213;
    end
end
assign V_bus_dataout = ap_const_lv128_lc_1;
assign V_bus_req_din = ap_const_logic_0;
assign V_bus_size = ap_const_lv32_0;
assign a_addr1_fu_819_p2 = (a_addr9_cast_reg_979 + tmp_15_trn_cast_fu_815_p1);
assign a_addr2_cast_fu_491_p1 = {{1{1'b0}}, {a_addr2_fu_485_p2}};
assign a_addr2_fu_485_p2 = tmp_4_trn_cast_fu_479_p1 << ap_const_lv13_6;
assign a_addr3_fu_495_p2 = (a_addr2_cast_fu_491_p1 + tmp_22_trn_cast_fu_482_p1);
assign a_addr4_fu_796_p2 = (a_addr9_cast_reg_979 + tmp_13_trn_cast_fu_792_p1);
assign a_addr5_fu_519_p2 = (a_addr2_cast_fu_491_p1 + tmp_24_trn_cast_fu_515_p1);
assign a_addr6_fu_543_p2 = (a_addr2_cast_reg_909 + tmp_26_trn_cast_fu_539_p1);
assign a_addr7_fu_772_p2 = (a_addr9_cast_fu_744_p1 + tmp_11_trn_cast_fu_768_p1);
assign a_addr8_fu_566_p2 = (a_addr2_cast_reg_909 + tmp_28_trn_cast_fu_562_p1);
assign a_addr9_cast_fu_744_p1 = {{1{1'b0}}, {a_addr9_fu_738_p2}};
assign a_addr9_fu_738_p2 = tmp_3_trn8_cast_fu_732_p1 << ap_const_lv13_6;
assign a_addr_fu_748_p2 = (a_addr9_cast_fu_744_p1 + tmp_trn_cast_fu_735_p1);

/// ap_sig_bdd_119 assign process. ///
always @ (V_bus_req_full_n or exitcond2_reg_845)
begin
    ap_sig_bdd_119 = ((ap_const_lv1_0 == exitcond2_reg_845) & (V_bus_req_full_n == ap_const_logic_0));
end

/// ap_sig_bdd_151 assign process. ///
always @ (V_bus_rsp_empty_n or exitcond_reg_915)
begin
    ap_sig_bdd_151 = ((V_bus_rsp_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_reg_915));
end

/// ap_sig_bdd_183 assign process. ///
always @ (V_bus_req_full_n or exitcond_reg_915)
begin
    ap_sig_bdd_183 = ((V_bus_req_full_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_reg_915));
end

/// ap_sig_bdd_86 assign process. ///
always @ (V_bus_rsp_empty_n or exitcond2_reg_845)
begin
    ap_sig_bdd_86 = ((V_bus_rsp_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond2_reg_845));
end
assign counter_cast2_fu_307_p1 = {{12{1'b0}}, {counter}};
assign counter_cast_fu_293_p1 = {{12{1'b0}}, {counter}};
assign exitcond1_fu_588_p2 = (indvar_phi_fu_250_p4 == ap_const_lv5_10? 1'b1: 1'b0);
assign exitcond2_fu_327_p2 = (indvar_flatten_phi_fu_184_p4 == ap_const_lv11_400? 1'b1: 1'b0);
assign exitcond3_fu_339_p2 = (indvar1_phi_fu_206_p4 == ap_const_lv5_10? 1'b1: 1'b0);
assign exitcond_fu_576_p2 = (indvar_flatten1_phi_fu_228_p4 == ap_const_lv11_400? 1'b1: 1'b0);
assign i_1_cast_fu_624_p1 = {{6{1'b0}}, {i_1_mid2_fu_616_p3}};
assign i_1_mid2_fu_616_p3 = ((exitcond1_fu_588_p2)? tmp_5_dup_fu_610_p2: i_1_phi_fu_239_p4);
assign i_cast_fu_375_p1 = {{6{1'b0}}, {i_mid2_fu_367_p3}};
assign i_mid2_fu_367_p3 = ((exitcond3_fu_339_p2)? tmp_17_dup_fu_361_p2: i_phi_fu_195_p4);
assign icmp_fu_281_p2 = (tmp_8_fu_277_p1 == ap_const_lv2_1? 1'b1: 1'b0);
assign indvar1_cast_fu_385_p1 = {{2{1'b0}}, {indvar1_mid2_fu_345_p3}};
assign indvar1_mid2_fu_345_p3 = ((exitcond3_fu_339_p2)? ap_const_lv5_0: indvar1_phi_fu_206_p4);
assign indvar_cast_fu_634_p1 = {{2{1'b0}}, {indvar_mid2_fu_594_p3}};
assign indvar_mid2_fu_594_p3 = ((exitcond1_fu_588_p2)? ap_const_lv5_0: indvar_phi_fu_250_p4);
assign tmp10_fu_811_p1 = p_3_reg_969;
assign tmp11_cast_fu_405_p1 = {{7{1'b0}}, {tmp11_fu_399_p2}};
assign tmp11_fu_399_p2 = (tmp6_fu_379_p2 + tmp7_cast_fu_395_p1);
assign tmp12_fu_535_p1 = p_5_reg_894;
assign tmp13_fu_409_p2 = (tmp11_cast_fu_405_p1 + tmp3_cast_reg_835);
assign tmp14_fu_788_p1 = p_2_reg_964;
assign tmp15_fu_728_p1 = tmp_9_reg_954;
assign tmp16_fu_511_p1 = p_4_reg_889;
assign tmp17_fu_764_p1 = p_1_reg_959;
assign tmp18_fu_475_p1 = tmp_17_reg_884;
assign tmp1_cast_fu_317_p1 = {{1{1'b0}}, {tmp1_fu_311_p2}};
assign tmp1_fu_311_p2 = counter_cast2_fu_307_p1 << ap_const_lv19_C;
assign tmp2_fu_321_p2 = (ap_const_lv20_3F000 - tmp1_cast_fu_317_p1);
assign tmp3_cast_fu_303_p1 = {{1{1'b0}}, {tmp3_fu_297_p2}};
assign tmp3_fu_297_p2 = counter_cast_fu_293_p1 << ap_const_lv19_C;
assign tmp4_fu_628_p2 = i_1_cast_fu_624_p1 << ap_const_lv13_6;
assign tmp5_cast_cast_fu_654_p1 = {{7{1'b0}}, {tmp5_fu_648_p2}};
assign tmp5_fu_648_p2 = (tmp4_fu_628_p2 + tmp_cast_fu_644_p1);
assign tmp6_fu_379_p2 = i_cast_fu_375_p1 << ap_const_lv13_6;
assign tmp7_cast_fu_395_p1 = {{6{1'b0}}, {tmp7_fu_389_p2}};
assign tmp7_fu_389_p2 = indvar1_cast_fu_385_p1 << ap_const_lv7_2;
assign tmp8_fu_558_p1 = p_6_reg_899;
assign tmp9_fu_658_p2 = (tmp5_cast_cast_fu_654_p1 + tmp2_reg_840);
assign tmp_10_fu_801_p1 = {{50{1'b0}}, {a_addr4_fu_796_p2}};
assign tmp_11_fu_806_p2 = (ap_reg_ppstg_j_1_mid2_reg_924_pp1_it1 | ap_const_lv7_3);
assign tmp_11_trn_cast_fu_768_p1 = {{7{1'b0}}, {tmp_s_fu_759_p2}};
assign tmp_12_fu_824_p1 = {{50{1'b0}}, {a_addr1_fu_819_p2}};
assign tmp_13_fu_723_p2 = (j_1_mid2_reg_924 + ap_const_lv7_4);
assign tmp_13_trn_cast_fu_792_p1 = {{7{1'b0}}, {tmp_5_fu_783_p2}};
assign tmp_15_fu_420_p2 = tmp13_reg_869 >> ap_const_lv20_2;
assign tmp_15_trn_cast_fu_815_p1 = {{7{1'b0}}, {tmp_11_fu_806_p2}};
assign tmp_16_fu_425_p1 = {{44{1'b0}}, {tmp_15_fu_420_p2}};
assign tmp_17_dup_fu_361_p2 = (i_phi_fu_195_p4 + ap_const_lv7_1);
assign tmp_18_fu_501_p1 = {{50{1'b0}}, {a_addr3_fu_495_p2}};
assign tmp_19_fu_506_p2 = (ap_reg_ppstg_j_mid2_reg_854_pp0_it1 | ap_const_lv7_1);
assign tmp_1_fu_269_p3 = counter[ap_const_lv32_6];
assign tmp_20_fu_525_p1 = {{50{1'b0}}, {a_addr5_fu_519_p2}};
assign tmp_21_fu_530_p2 = (ap_reg_ppstg_j_mid2_reg_854_pp0_it1 | ap_const_lv7_2);
assign tmp_22_fu_548_p1 = {{50{1'b0}}, {a_addr6_fu_543_p2}};
assign tmp_22_trn_cast_fu_482_p1 = {{7{1'b0}}, {ap_reg_ppstg_j_mid2_reg_854_pp0_it1}};
assign tmp_23_fu_553_p2 = (ap_reg_ppstg_j_mid2_reg_854_pp0_it1 | ap_const_lv7_3);
assign tmp_24_fu_571_p1 = {{50{1'b0}}, {a_addr8_fu_566_p2}};
assign tmp_24_trn_cast_fu_515_p1 = {{7{1'b0}}, {tmp_19_fu_506_p2}};
assign tmp_25_fu_470_p2 = (j_mid2_reg_854 + ap_const_lv7_4);
assign tmp_26_trn_cast_fu_539_p1 = {{7{1'b0}}, {tmp_21_fu_530_p2}};
assign tmp_28_trn_cast_fu_562_p1 = {{7{1'b0}}, {tmp_23_fu_553_p2}};
assign tmp_2_fu_287_p2 = (tag == ap_const_lv2_0? 1'b1: 1'b0);
assign tmp_3_fu_754_p1 = {{50{1'b0}}, {a_addr_fu_748_p2}};
assign tmp_3_trn8_cast_fu_732_p1 = {{6{1'b0}}, {ap_reg_ppstg_i_1_mid2_reg_933_pp1_it1}};
assign tmp_4_fu_778_p1 = {{50{1'b0}}, {a_addr7_fu_772_p2}};
assign tmp_4_trn_cast_fu_479_p1 = {{6{1'b0}}, {ap_reg_ppstg_i_mid2_reg_863_pp0_it1}};
assign tmp_5_dup_fu_610_p2 = (i_1_phi_fu_239_p4 + ap_const_lv7_1);
assign tmp_5_fu_783_p2 = (ap_reg_ppstg_j_1_mid2_reg_924_pp1_it1 | ap_const_lv7_2);
assign tmp_7_fu_679_p1 = {{46{tmp_26_reg_939[17]}}, {tmp_26_reg_939}};
assign tmp_8_fu_277_p1 = {{1{1'b0}}, {tmp_1_fu_269_p3}};
assign tmp_cast_fu_644_p1 = {{6{1'b0}}, {tmp_fu_638_p2}};
assign tmp_fu_638_p2 = indvar_cast_fu_634_p1 << ap_const_lv7_2;
assign tmp_s_fu_759_p2 = (ap_reg_ppstg_j_1_mid2_reg_924_pp1_it1 | ap_const_lv7_1);
assign tmp_trn_cast_fu_735_p1 = {{7{1'b0}}, {ap_reg_ppstg_j_1_mid2_reg_924_pp1_it1}};
always @ (ap_clk)
begin
    tmp3_cast_reg_835[0] <= 1'b0;
    tmp3_cast_reg_835[1] <= 1'b0;
    tmp3_cast_reg_835[2] <= 1'b0;
    tmp3_cast_reg_835[3] <= 1'b0;
    tmp3_cast_reg_835[4] <= 1'b0;
    tmp3_cast_reg_835[5] <= 1'b0;
    tmp3_cast_reg_835[6] <= 1'b0;
    tmp3_cast_reg_835[7] <= 1'b0;
    tmp3_cast_reg_835[8] <= 1'b0;
    tmp3_cast_reg_835[9] <= 1'b0;
    tmp3_cast_reg_835[10] <= 1'b0;
    tmp3_cast_reg_835[11] <= 1'b0;
    tmp3_cast_reg_835[19] <= 1'b0;
end

always @ (ap_clk)
begin
    tmp2_reg_840[0] <= 1'b0;
    tmp2_reg_840[1] <= 1'b0;
    tmp2_reg_840[2] <= 1'b0;
    tmp2_reg_840[3] <= 1'b0;
    tmp2_reg_840[4] <= 1'b0;
    tmp2_reg_840[5] <= 1'b0;
    tmp2_reg_840[6] <= 1'b0;
    tmp2_reg_840[7] <= 1'b0;
    tmp2_reg_840[8] <= 1'b0;
    tmp2_reg_840[9] <= 1'b0;
    tmp2_reg_840[10] <= 1'b0;
    tmp2_reg_840[11] <= 1'b0;
end

always @ (ap_clk)
begin
    tmp13_reg_869[0] <= 1'b0;
    tmp13_reg_869[1] <= 1'b0;
end

always @ (ap_clk)
begin
    a_addr2_cast_reg_909[0] <= 1'b0;
    a_addr2_cast_reg_909[1] <= 1'b0;
    a_addr2_cast_reg_909[2] <= 1'b0;
    a_addr2_cast_reg_909[3] <= 1'b0;
    a_addr2_cast_reg_909[4] <= 1'b0;
    a_addr2_cast_reg_909[5] <= 1'b0;
    a_addr2_cast_reg_909[13] <= 1'b0;
end

always @ (ap_clk)
begin
    a_addr9_cast_reg_979[0] <= 1'b0;
    a_addr9_cast_reg_979[1] <= 1'b0;
    a_addr9_cast_reg_979[2] <= 1'b0;
    a_addr9_cast_reg_979[3] <= 1'b0;
    a_addr9_cast_reg_979[4] <= 1'b0;
    a_addr9_cast_reg_979[5] <= 1'b0;
    a_addr9_cast_reg_979[13] <= 1'b0;
end



endmodule //fetch

