// ==============================================================
// RTL generated by AutoESL - High-Level Synthesis System (C, C++, SystemC)
// Version: 2011.1
// Copyright (C) 2011 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module write_r (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        tag,
        counter,
        d_address0,
        d_ce0,
        d_q0,
        d_address1,
        d_ce1,
        d_q1,
        V_bus_req_din,
        V_bus_req_full_n,
        V_bus_req_write,
        V_bus_rsp_dout,
        V_bus_rsp_empty_n,
        V_bus_rsp_read,
        V_bus_address,
        V_bus_datain,
        V_bus_dataout,
        V_bus_size
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
input  [1:0] tag;
input  [6:0] counter;
output  [11:0] d_address0;
output   d_ce0;
input  [31:0] d_q0;
output  [11:0] d_address1;
output   d_ce1;
input  [31:0] d_q1;
output   V_bus_req_din;
input   V_bus_req_full_n;
output   V_bus_req_write;
input   V_bus_rsp_dout;
input   V_bus_rsp_empty_n;
output   V_bus_rsp_read;
output  [31:0] V_bus_address;
input  [127:0] V_bus_datain;
output  [127:0] V_bus_dataout;
output  [31:0] V_bus_size;

reg ap_done;
reg ap_idle;
reg[11:0] d_address0;
reg d_ce0;
reg[11:0] d_address1;
reg d_ce1;
reg V_bus_req_din;
reg V_bus_req_write;
reg[31:0] V_bus_address;
reg[127:0] V_bus_dataout;
reg   [2:0] ap_CS_fsm;
reg   [10:0] indvar_flatten1_reg_135;
reg   [6:0] i_1_reg_146;
reg   [4:0] indvar_reg_157;
reg   [6:0] j_1_reg_168;
reg   [10:0] indvar_flatten_reg_179;
reg   [6:0] i_reg_190;
reg   [4:0] indvar1_reg_201;
reg   [6:0] j_reg_212;
reg   [31:0] reg_224;
reg    ap_reg_ppiten_pp0_it2;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg   [0:0] exitcond2_reg_672;
reg   [0:0] ap_reg_ppstg_exitcond2_reg_672_pp0_it2;
reg    ap_sig_bdd_73;
reg    ap_reg_ppiten_pp0_it3;
reg    ap_reg_ppiten_pp0_it4;
reg   [0:0] ap_reg_ppstg_exitcond2_reg_672_pp0_it1;
reg    ap_reg_ppiten_pp1_it2;
reg    ap_reg_ppiten_pp1_it0;
reg    ap_reg_ppiten_pp1_it1;
reg   [0:0] exitcond_reg_736;
reg   [0:0] ap_reg_ppstg_exitcond_reg_736_pp1_it2;
reg    ap_sig_bdd_96;
reg    ap_reg_ppiten_pp1_it3;
reg    ap_reg_ppiten_pp1_it4;
reg   [0:0] ap_reg_ppstg_exitcond_reg_736_pp1_it1;
reg   [31:0] reg_228;
wire   [19:0] tmp1_cast_fu_266_p1;
reg   [19:0] tmp1_cast_reg_662;
wire   [0:0] or_cond_fu_244_p2;
wire   [19:0] tmp3_fu_270_p2;
reg   [19:0] tmp3_reg_667;
wire   [0:0] tmp_3_fu_250_p2;
wire   [0:0] exitcond2_fu_276_p2;
reg   [10:0] indvar_flatten_next1_reg_676;
reg   [4:0] indvar_mid2_reg_681;
reg   [4:0] ap_reg_ppstg_indvar_mid2_reg_681_pp0_it1;
reg   [6:0] j_1_mid2_reg_687;
reg   [6:0] i_1_mid2_reg_694;
reg   [6:0] ap_reg_ppstg_i_1_mid2_reg_694_pp0_it1;
wire   [6:0] tmp_18_fu_371_p2;
wire   [4:0] indvar_next_fu_376_p2;
reg   [17:0] tmp_16_reg_721;
wire   [127:0] tmp_15_fu_444_p1;
wire   [0:0] exitcond_fu_459_p2;
reg   [10:0] indvar_flatten_next_reg_740;
reg   [4:0] indvar1_mid2_reg_745;
reg   [4:0] ap_reg_ppstg_indvar1_mid2_reg_745_pp1_it1;
reg   [6:0] j_mid2_reg_751;
reg   [6:0] i_mid2_reg_758;
reg   [6:0] ap_reg_ppstg_i_mid2_reg_758_pp1_it1;
wire   [6:0] tmp_10_fu_554_p2;
wire   [4:0] indvar_next1_fu_559_p2;
reg   [19:0] tmp_7_reg_785;
wire   [127:0] tmp_s_fu_641_p1;
reg   [10:0] indvar_flatten1_phi_fu_139_p4;
reg   [6:0] i_1_phi_fu_150_p4;
reg   [4:0] indvar_phi_fu_161_p4;
reg   [6:0] j_1_phi_fu_172_p4;
reg   [10:0] indvar_flatten_phi_fu_183_p4;
reg   [6:0] i_phi_fu_194_p4;
reg   [4:0] indvar1_phi_fu_205_p4;
reg   [6:0] j_phi_fu_216_p4;
wire   [63:0] tmp_12_fu_346_p1;
wire   [63:0] tmp_14_fu_366_p1;
wire   [63:0] tmp_5_fu_529_p1;
wire   [63:0] tmp_6_fu_549_p1;
wire   [63:0] tmp_17_fu_449_p1;
wire   [63:0] tmp_9_fu_646_p1;
wire   [0:0] tmp_1_fu_232_p2;
wire   [0:0] tmp_2_fu_238_p2;
wire   [18:0] counter_cast_fu_256_p1;
wire   [18:0] tmp1_fu_260_p2;
wire   [0:0] exitcond3_fu_288_p2;
wire   [6:0] tmp_13_dup_fu_310_p2;
wire   [12:0] tmp_5_trn2_cast_fu_324_p1;
wire   [12:0] d_addr3_fu_330_p2;
wire   [13:0] d_addr3_cast_fu_336_p1;
wire   [13:0] tmp_14_trn_cast_fu_327_p1;
wire   [13:0] d_addr4_fu_340_p2;
wire   [6:0] tmp_13_fu_351_p2;
wire   [13:0] tmp_16_trn_cast_fu_356_p1;
wire   [13:0] d_addr1_fu_360_p2;
wire   [12:0] i_1_cast_fu_381_p1;
wire   [6:0] indvar_cast_fu_390_p1;
wire   [6:0] tmp_fu_393_p2;
wire   [12:0] tmp6_fu_384_p2;
wire   [12:0] tmp_cast_fu_399_p1;
wire   [12:0] tmp7_fu_403_p2;
wire   [19:0] tmp7_cast_cast_fu_409_p1;
wire   [19:0] tmp10_fu_413_p2;
wire   [31:0] tmp13_fu_432_p1;
wire   [31:0] tmp14_fu_428_p1;
wire   [63:0] p_0_fu_436_p3;
wire   [0:0] exitcond1_fu_471_p2;
wire   [6:0] tmp_6_dup_fu_493_p2;
wire   [12:0] tmp_4_trn7_cast_fu_507_p1;
wire   [12:0] d_addr8_fu_513_p2;
wire   [13:0] d_addr8_cast_fu_519_p1;
wire   [13:0] tmp_7_trn_cast_fu_510_p1;
wire   [13:0] d_addr9_fu_523_p2;
wire   [6:0] tmp_8_fu_534_p2;
wire   [13:0] tmp_9_trn_cast_fu_539_p1;
wire   [13:0] d_addr6_fu_543_p2;
wire   [12:0] i_cast_fu_564_p1;
wire   [12:0] tmp4_fu_567_p2;
wire   [19:0] tmp4_cast_fu_573_p1;
wire   [19:0] tmp2_fu_577_p2;
wire   [6:0] indvar1_cast_fu_586_p1;
wire   [6:0] tmp8_fu_589_p2;
wire   [14:0] tmp8_cast_fu_595_p1;
wire   [14:0] tmp5_fu_599_p2;
wire   [21:0] tmp9_fu_609_p0;
wire   [21:0] tmp2_cast_fu_582_p1;
wire   [21:0] tmp9_fu_609_p2;
wire   [31:0] tmp11_fu_629_p1;
wire   [31:0] tmp12_fu_625_p1;
wire   [63:0] p_s_fu_633_p3;
reg   [2:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st0_fsm_0 = 3'b000;
parameter    ap_ST_st1_fsm_1 = 3'b001;
parameter    ap_ST_pp0_stg0_fsm_2 = 3'b010;
parameter    ap_ST_pp1_stg0_fsm_3 = 3'b011;
parameter    ap_ST_st12_fsm_4 = 3'b100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv7_43 = 7'b1000011;
parameter    ap_const_lv7_2 = 7'b0000010;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv19_C = 19'b0000000000000001100;
parameter    ap_const_lv20_42000 = 20'b01000010000000000000;
parameter    ap_const_lv11_400 = 11'b10000000000;
parameter    ap_const_lv11_1 = 11'b00000000001;
parameter    ap_const_lv5_10 = 5'b10000;
parameter    ap_const_lv7_1 = 7'b0000001;
parameter    ap_const_lv13_6 = 13'b0000000000110;
parameter    ap_const_lv7_4 = 7'b0000100;
parameter    ap_const_lv5_1 = 5'b00001;
parameter    ap_const_lv32_2 = 32'b00000000000000000000000000000010;
parameter    ap_const_lv32_13 = 32'b00000000000000000000000000010011;
parameter    ap_const_lv15_5000 = 15'b101000000000000;
parameter    ap_const_lv32_15 = 32'b00000000000000000000000000010101;
parameter    ap_true = 1'b1;




/// ap_CS_fsm assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & ~(ap_const_lv1_0 == exitcond2_fu_276_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & (ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (ap_const_lv1_0 == exitcond2_fu_276_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & (ap_const_lv1_0 == tmp_3_fu_250_p2)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & ~(ap_const_lv1_0 == exitcond2_fu_276_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & (ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
            ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & (ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
            ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & (ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
            ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp1_it0 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & ~(ap_const_lv1_0 == exitcond_fu_459_p2))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & ~(ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp1_it1 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == exitcond_fu_459_p2))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & ~(ap_const_lv1_0 == tmp_3_fu_250_p2)) | ((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & ~(ap_const_lv1_0 == exitcond_fu_459_p2)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp1_it2 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)))) begin
            ap_reg_ppiten_pp1_it2 <= ap_reg_ppiten_pp1_it1;
        end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & ~(ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
            ap_reg_ppiten_pp1_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp1_it3 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it3 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)))) begin
            ap_reg_ppiten_pp1_it3 <= ap_reg_ppiten_pp1_it2;
        end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & ~(ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
            ap_reg_ppiten_pp1_it3 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp1_it4 assign process. ///
always @ (posedge ap_rst or posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it4 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)))) begin
            ap_reg_ppiten_pp1_it4 <= ap_reg_ppiten_pp1_it3;
        end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & ~(ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
            ap_reg_ppiten_pp1_it4 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
        ap_reg_ppstg_exitcond2_reg_672_pp0_it1 <= exitcond2_reg_672;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
        ap_reg_ppstg_exitcond2_reg_672_pp0_it2 <= ap_reg_ppstg_exitcond2_reg_672_pp0_it1;
    end
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)))) begin
        ap_reg_ppstg_exitcond_reg_736_pp1_it1 <= exitcond_reg_736;
    end
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)))) begin
        ap_reg_ppstg_exitcond_reg_736_pp1_it2 <= ap_reg_ppstg_exitcond_reg_736_pp1_it1;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
        ap_reg_ppstg_i_1_mid2_reg_694_pp0_it1 <= i_1_mid2_reg_694;
    end
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)))) begin
        ap_reg_ppstg_i_mid2_reg_758_pp1_it1 <= i_mid2_reg_758;
    end
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)))) begin
        ap_reg_ppstg_indvar1_mid2_reg_745_pp1_it1 <= indvar1_mid2_reg_745;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
        ap_reg_ppstg_indvar_mid2_reg_681_pp0_it1 <= indvar_mid2_reg_681;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
        exitcond2_reg_672 <= (indvar_flatten1_phi_fu_139_p4 == ap_const_lv11_400? 1'b1: 1'b0);
    end
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)))) begin
        exitcond_reg_736 <= (indvar_flatten_phi_fu_183_p4 == ap_const_lv11_400? 1'b1: 1'b0);
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (ap_const_lv1_0 == exitcond2_fu_276_p2))) begin
        if (exitcond3_fu_288_p2) begin
            i_1_mid2_reg_694 <= tmp_13_dup_fu_310_p2;
        end else begin
            i_1_mid2_reg_694 <= i_1_phi_fu_150_p4;
        end

    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (exitcond2_reg_672 == ap_const_lv1_0))) begin
        i_1_reg_146 <= i_1_mid2_reg_694;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & (ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
        i_1_reg_146 <= ap_const_lv7_0;
    end
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == exitcond_fu_459_p2))) begin
        if (exitcond1_fu_471_p2) begin
            i_mid2_reg_758 <= tmp_6_dup_fu_493_p2;
        end else begin
            i_mid2_reg_758 <= i_phi_fu_194_p4;
        end

    end
    if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & ~(ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
        i_reg_190 <= ap_const_lv7_0;
    end else if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == exitcond_reg_736))) begin
        i_reg_190 <= i_mid2_reg_758;
    end
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == exitcond_fu_459_p2))) begin
        if (exitcond1_fu_471_p2) begin
            indvar1_mid2_reg_745 <= ap_const_lv5_0;
        end else begin
            indvar1_mid2_reg_745 <= indvar1_phi_fu_205_p4;
        end

    end
    if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & ~(ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
        indvar1_reg_201 <= ap_const_lv5_0;
    end else if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == exitcond_reg_736))) begin
        indvar1_reg_201 <= (indvar1_mid2_reg_745 + ap_const_lv5_1);
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (exitcond2_reg_672 == ap_const_lv1_0))) begin
        indvar_flatten1_reg_135 <= indvar_flatten_next1_reg_676;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & (ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
        indvar_flatten1_reg_135 <= ap_const_lv11_0;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
        indvar_flatten_next1_reg_676 <= (indvar_flatten1_phi_fu_139_p4 + ap_const_lv11_1);
    end
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)))) begin
        indvar_flatten_next_reg_740 <= (indvar_flatten_phi_fu_183_p4 + ap_const_lv11_1);
    end
    if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & ~(ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
        indvar_flatten_reg_179 <= ap_const_lv11_0;
    end else if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == exitcond_reg_736))) begin
        indvar_flatten_reg_179 <= indvar_flatten_next_reg_740;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (ap_const_lv1_0 == exitcond2_fu_276_p2))) begin
        if (exitcond3_fu_288_p2) begin
            indvar_mid2_reg_681 <= ap_const_lv5_0;
        end else begin
            indvar_mid2_reg_681 <= indvar_phi_fu_161_p4;
        end

    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (exitcond2_reg_672 == ap_const_lv1_0))) begin
        indvar_reg_157 <= (indvar_mid2_reg_681 + ap_const_lv5_1);
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & (ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
        indvar_reg_157 <= ap_const_lv5_0;
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (ap_const_lv1_0 == exitcond2_fu_276_p2))) begin
        if (exitcond3_fu_288_p2) begin
            j_1_mid2_reg_687 <= ap_const_lv7_0;
        end else begin
            j_1_mid2_reg_687 <= j_1_phi_fu_172_p4;
        end

    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (exitcond2_reg_672 == ap_const_lv1_0))) begin
        j_1_reg_168 <= (j_1_mid2_reg_687 + ap_const_lv7_4);
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & (ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
        j_1_reg_168 <= ap_const_lv7_0;
    end
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == exitcond_fu_459_p2))) begin
        if (exitcond1_fu_471_p2) begin
            j_mid2_reg_751 <= ap_const_lv7_0;
        end else begin
            j_mid2_reg_751 <= j_phi_fu_216_p4;
        end

    end
    if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & ~(ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
        j_reg_212 <= ap_const_lv7_0;
    end else if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == exitcond_reg_736))) begin
        j_reg_212 <= (j_mid2_reg_751 + ap_const_lv7_4);
    end
    if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_672_pp0_it1)) | ((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_736_pp1_it1)))) begin
        reg_224 <= d_q0;
    end
    if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_672_pp0_it1)) | ((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_736_pp1_it1)))) begin
        reg_228 <= d_q1;
    end
    if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2))) begin
        tmp1_cast_reg_662[12] <= tmp1_cast_fu_266_p1[12];
        tmp1_cast_reg_662[13] <= tmp1_cast_fu_266_p1[13];
        tmp1_cast_reg_662[14] <= tmp1_cast_fu_266_p1[14];
        tmp1_cast_reg_662[15] <= tmp1_cast_fu_266_p1[15];
        tmp1_cast_reg_662[16] <= tmp1_cast_fu_266_p1[16];
        tmp1_cast_reg_662[17] <= tmp1_cast_fu_266_p1[17];
        tmp1_cast_reg_662[18] <= tmp1_cast_fu_266_p1[18];
    end
    if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & (ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
        tmp3_reg_667[12] <= tmp3_fu_270_p2[12];
        tmp3_reg_667[13] <= tmp3_fu_270_p2[13];
        tmp3_reg_667[14] <= tmp3_fu_270_p2[14];
        tmp3_reg_667[15] <= tmp3_fu_270_p2[15];
        tmp3_reg_667[16] <= tmp3_fu_270_p2[16];
        tmp3_reg_667[17] <= tmp3_fu_270_p2[17];
        tmp3_reg_667[18] <= tmp3_fu_270_p2[18];
        tmp3_reg_667[19] <= tmp3_fu_270_p2[19];
    end
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_672_pp0_it1))) begin
        tmp_16_reg_721 <= {{tmp10_fu_413_p2[ap_const_lv32_13 : ap_const_lv32_2]}};
    end
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_736_pp1_it1))) begin
        tmp_7_reg_785 <= {{tmp9_fu_609_p2[ap_const_lv32_15 : ap_const_lv32_2]}};
    end
end

/// V_bus_address assign process. ///
always @ (ap_CS_fsm or ap_reg_ppstg_exitcond2_reg_672_pp0_it2 or ap_sig_bdd_73 or ap_reg_ppiten_pp0_it3 or ap_reg_ppstg_exitcond_reg_736_pp1_it2 or ap_sig_bdd_96 or ap_reg_ppiten_pp1_it3 or tmp_17_fu_449_p1 or tmp_9_fu_646_p1)
begin
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_736_pp1_it2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)))) begin
        V_bus_address = tmp_9_fu_646_p1;
    end else if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_reg_ppstg_exitcond2_reg_672_pp0_it2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
        V_bus_address = tmp_17_fu_449_p1;
    end else begin
        V_bus_address = tmp_9_fu_646_p1;
    end
end

/// V_bus_dataout assign process. ///
always @ (ap_CS_fsm or ap_reg_ppstg_exitcond2_reg_672_pp0_it2 or ap_sig_bdd_73 or ap_reg_ppiten_pp0_it3 or ap_reg_ppstg_exitcond_reg_736_pp1_it2 or ap_sig_bdd_96 or ap_reg_ppiten_pp1_it3 or tmp_15_fu_444_p1 or tmp_s_fu_641_p1)
begin
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_736_pp1_it2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)))) begin
        V_bus_dataout = tmp_s_fu_641_p1;
    end else if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_reg_ppstg_exitcond2_reg_672_pp0_it2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
        V_bus_dataout = tmp_15_fu_444_p1;
    end else begin
        V_bus_dataout = tmp_s_fu_641_p1;
    end
end

/// V_bus_req_din assign process. ///
always @ (ap_CS_fsm or ap_reg_ppstg_exitcond2_reg_672_pp0_it2 or ap_sig_bdd_73 or ap_reg_ppiten_pp0_it3 or ap_reg_ppstg_exitcond_reg_736_pp1_it2 or ap_sig_bdd_96 or ap_reg_ppiten_pp1_it3)
begin
    if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_reg_ppstg_exitcond2_reg_672_pp0_it2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))) | ((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_736_pp1_it2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3))))) begin
        V_bus_req_din = ap_const_logic_1;
    end else begin
        V_bus_req_din = ap_const_logic_0;
    end
end

/// V_bus_req_write assign process. ///
always @ (ap_CS_fsm or ap_reg_ppstg_exitcond2_reg_672_pp0_it2 or ap_sig_bdd_73 or ap_reg_ppiten_pp0_it3 or ap_reg_ppstg_exitcond_reg_736_pp1_it2 or ap_sig_bdd_96 or ap_reg_ppiten_pp1_it3)
begin
    if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_reg_ppstg_exitcond2_reg_672_pp0_it2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))) | ((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_736_pp1_it2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3))))) begin
        V_bus_req_write = ap_const_logic_1;
    end else begin
        V_bus_req_write = ap_const_logic_0;
    end
end

/// ap_NS_fsm assign process. ///
always @ (ap_start or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_73 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_sig_bdd_96 or ap_reg_ppiten_pp1_it3 or ap_reg_ppiten_pp1_it4 or or_cond_fu_244_p2 or tmp_3_fu_250_p2 or exitcond2_fu_276_p2 or exitcond_fu_459_p2)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st12_fsm_4 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st0_fsm_0;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & (ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
        ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == or_cond_fu_244_p2) & ~(ap_const_lv1_0 == tmp_3_fu_250_p2))) begin
        ap_NS_fsm = ap_ST_pp1_stg0_fsm_3;
    end else if ((((ap_ST_st1_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == or_cond_fu_244_p2)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & ~(ap_const_lv1_0 == exitcond2_fu_276_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it4) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) | ((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & ~(ap_const_lv1_0 == exitcond_fu_459_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        ap_NS_fsm = ap_ST_st12_fsm_4;
    end else if ((((ap_ST_st0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_start)) | ((ap_const_logic_1 == ap_start) & (ap_ST_st12_fsm_4 == ap_CS_fsm)))) begin
        ap_NS_fsm = ap_ST_st1_fsm_1;
    end else begin
        ap_NS_fsm = ap_CS_fsm;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st0_fsm_0 == ap_CS_fsm) | (ap_ST_st12_fsm_4 == ap_CS_fsm))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st0_fsm_0 == ap_CS_fsm)) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// d_address0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it1 or exitcond2_reg_672 or ap_sig_bdd_73 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp1_it1 or exitcond_reg_736 or ap_sig_bdd_96 or ap_reg_ppiten_pp1_it3 or tmp_12_fu_346_p1 or tmp_5_fu_529_p1)
begin
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == exitcond_reg_736))) begin
        d_address0 = tmp_5_fu_529_p1;
    end else if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (exitcond2_reg_672 == ap_const_lv1_0))) begin
        d_address0 = tmp_12_fu_346_p1;
    end else begin
        d_address0 = tmp_5_fu_529_p1;
    end
end

/// d_address1 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it1 or exitcond2_reg_672 or ap_sig_bdd_73 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp1_it1 or exitcond_reg_736 or ap_sig_bdd_96 or ap_reg_ppiten_pp1_it3 or tmp_14_fu_366_p1 or tmp_6_fu_549_p1)
begin
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == exitcond_reg_736))) begin
        d_address1 = tmp_6_fu_549_p1;
    end else if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (exitcond2_reg_672 == ap_const_lv1_0))) begin
        d_address1 = tmp_14_fu_366_p1;
    end else begin
        d_address1 = tmp_6_fu_549_p1;
    end
end

/// d_ce0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it1 or exitcond2_reg_672 or ap_sig_bdd_73 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp1_it1 or exitcond_reg_736 or ap_sig_bdd_96 or ap_reg_ppiten_pp1_it3)
begin
    if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (exitcond2_reg_672 == ap_const_lv1_0)) | ((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == exitcond_reg_736)))) begin
        d_ce0 = ap_const_logic_1;
    end else begin
        d_ce0 = ap_const_logic_0;
    end
end

/// d_ce1 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it1 or exitcond2_reg_672 or ap_sig_bdd_73 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp1_it1 or exitcond_reg_736 or ap_sig_bdd_96 or ap_reg_ppiten_pp1_it3)
begin
    if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_73 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & (exitcond2_reg_672 == ap_const_lv1_0)) | ((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it3)) & (ap_const_lv1_0 == exitcond_reg_736)))) begin
        d_ce1 = ap_const_logic_1;
    end else begin
        d_ce1 = ap_const_logic_0;
    end
end

/// i_1_phi_fu_150_p4 assign process. ///
always @ (ap_CS_fsm or i_1_reg_146 or ap_reg_ppiten_pp0_it1 or exitcond2_reg_672 or i_1_mid2_reg_694)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond2_reg_672 == ap_const_lv1_0))) begin
        i_1_phi_fu_150_p4 = i_1_mid2_reg_694;
    end else begin
        i_1_phi_fu_150_p4 = i_1_reg_146;
    end
end

/// i_phi_fu_194_p4 assign process. ///
always @ (ap_CS_fsm or i_reg_190 or ap_reg_ppiten_pp1_it1 or exitcond_reg_736 or i_mid2_reg_758)
begin
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_reg_736))) begin
        i_phi_fu_194_p4 = i_mid2_reg_758;
    end else begin
        i_phi_fu_194_p4 = i_reg_190;
    end
end

/// indvar1_phi_fu_205_p4 assign process. ///
always @ (ap_CS_fsm or indvar1_reg_201 or ap_reg_ppiten_pp1_it1 or exitcond_reg_736 or indvar_next1_fu_559_p2)
begin
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_reg_736))) begin
        indvar1_phi_fu_205_p4 = indvar_next1_fu_559_p2;
    end else begin
        indvar1_phi_fu_205_p4 = indvar1_reg_201;
    end
end

/// indvar_flatten1_phi_fu_139_p4 assign process. ///
always @ (ap_CS_fsm or indvar_flatten1_reg_135 or ap_reg_ppiten_pp0_it1 or exitcond2_reg_672 or indvar_flatten_next1_reg_676)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond2_reg_672 == ap_const_lv1_0))) begin
        indvar_flatten1_phi_fu_139_p4 = indvar_flatten_next1_reg_676;
    end else begin
        indvar_flatten1_phi_fu_139_p4 = indvar_flatten1_reg_135;
    end
end

/// indvar_flatten_phi_fu_183_p4 assign process. ///
always @ (ap_CS_fsm or indvar_flatten_reg_179 or ap_reg_ppiten_pp1_it1 or exitcond_reg_736 or indvar_flatten_next_reg_740)
begin
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_reg_736))) begin
        indvar_flatten_phi_fu_183_p4 = indvar_flatten_next_reg_740;
    end else begin
        indvar_flatten_phi_fu_183_p4 = indvar_flatten_reg_179;
    end
end

/// indvar_phi_fu_161_p4 assign process. ///
always @ (ap_CS_fsm or indvar_reg_157 or ap_reg_ppiten_pp0_it1 or exitcond2_reg_672 or indvar_next_fu_376_p2)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond2_reg_672 == ap_const_lv1_0))) begin
        indvar_phi_fu_161_p4 = indvar_next_fu_376_p2;
    end else begin
        indvar_phi_fu_161_p4 = indvar_reg_157;
    end
end

/// j_1_phi_fu_172_p4 assign process. ///
always @ (ap_CS_fsm or j_1_reg_168 or ap_reg_ppiten_pp0_it1 or exitcond2_reg_672 or tmp_18_fu_371_p2)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond2_reg_672 == ap_const_lv1_0))) begin
        j_1_phi_fu_172_p4 = tmp_18_fu_371_p2;
    end else begin
        j_1_phi_fu_172_p4 = j_1_reg_168;
    end
end

/// j_phi_fu_216_p4 assign process. ///
always @ (ap_CS_fsm or j_reg_212 or ap_reg_ppiten_pp1_it1 or exitcond_reg_736 or tmp_10_fu_554_p2)
begin
    if (((ap_ST_pp1_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_reg_736))) begin
        j_phi_fu_216_p4 = tmp_10_fu_554_p2;
    end else begin
        j_phi_fu_216_p4 = j_reg_212;
    end
end
assign V_bus_rsp_read = ap_const_logic_0;
assign V_bus_size = ap_const_lv32_0;

/// ap_sig_bdd_73 assign process. ///
always @ (V_bus_req_full_n or ap_reg_ppstg_exitcond2_reg_672_pp0_it2)
begin
    ap_sig_bdd_73 = ((V_bus_req_full_n == ap_const_logic_0) & (ap_reg_ppstg_exitcond2_reg_672_pp0_it2 == ap_const_lv1_0));
end

/// ap_sig_bdd_96 assign process. ///
always @ (V_bus_req_full_n or ap_reg_ppstg_exitcond_reg_736_pp1_it2)
begin
    ap_sig_bdd_96 = ((V_bus_req_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_736_pp1_it2));
end
assign counter_cast_fu_256_p1 = {{12{1'b0}}, {counter}};
assign d_addr1_fu_360_p2 = (d_addr3_cast_fu_336_p1 + tmp_16_trn_cast_fu_356_p1);
assign d_addr3_cast_fu_336_p1 = {{1{1'b0}}, {d_addr3_fu_330_p2}};
assign d_addr3_fu_330_p2 = tmp_5_trn2_cast_fu_324_p1 << ap_const_lv13_6;
assign d_addr4_fu_340_p2 = (d_addr3_cast_fu_336_p1 + tmp_14_trn_cast_fu_327_p1);
assign d_addr6_fu_543_p2 = (d_addr8_cast_fu_519_p1 + tmp_9_trn_cast_fu_539_p1);
assign d_addr8_cast_fu_519_p1 = {{1{1'b0}}, {d_addr8_fu_513_p2}};
assign d_addr8_fu_513_p2 = tmp_4_trn7_cast_fu_507_p1 << ap_const_lv13_6;
assign d_addr9_fu_523_p2 = (d_addr8_cast_fu_519_p1 + tmp_7_trn_cast_fu_510_p1);
assign exitcond1_fu_471_p2 = (indvar1_phi_fu_205_p4 == ap_const_lv5_10? 1'b1: 1'b0);
assign exitcond2_fu_276_p2 = (indvar_flatten1_phi_fu_139_p4 == ap_const_lv11_400? 1'b1: 1'b0);
assign exitcond3_fu_288_p2 = (indvar_phi_fu_161_p4 == ap_const_lv5_10? 1'b1: 1'b0);
assign exitcond_fu_459_p2 = (indvar_flatten_phi_fu_183_p4 == ap_const_lv11_400? 1'b1: 1'b0);
assign i_1_cast_fu_381_p1 = {{6{1'b0}}, {ap_reg_ppstg_i_1_mid2_reg_694_pp0_it1}};
assign i_cast_fu_564_p1 = {{6{1'b0}}, {ap_reg_ppstg_i_mid2_reg_758_pp1_it1}};
assign indvar1_cast_fu_586_p1 = {{2{1'b0}}, {ap_reg_ppstg_indvar1_mid2_reg_745_pp1_it1}};
assign indvar_cast_fu_390_p1 = {{2{1'b0}}, {ap_reg_ppstg_indvar_mid2_reg_681_pp0_it1}};
assign indvar_next1_fu_559_p2 = (indvar1_mid2_reg_745 + ap_const_lv5_1);
assign indvar_next_fu_376_p2 = (indvar_mid2_reg_681 + ap_const_lv5_1);
assign or_cond_fu_244_p2 = (tmp_1_fu_232_p2 & tmp_2_fu_238_p2);
assign p_0_fu_436_p3 = {{tmp13_fu_432_p1}, {tmp14_fu_428_p1}};
assign p_s_fu_633_p3 = {{tmp11_fu_629_p1}, {tmp12_fu_625_p1}};
assign tmp10_fu_413_p2 = (tmp7_cast_cast_fu_409_p1 + tmp3_reg_667);
assign tmp11_fu_629_p1 = reg_228;
assign tmp12_fu_625_p1 = reg_224;
assign tmp13_fu_432_p1 = reg_228;
assign tmp14_fu_428_p1 = reg_224;
assign tmp1_cast_fu_266_p1 = {{1{1'b0}}, {tmp1_fu_260_p2}};
assign tmp1_fu_260_p2 = counter_cast_fu_256_p1 << ap_const_lv19_C;
assign tmp2_cast_fu_582_p1 = {{2{1'b0}}, {tmp2_fu_577_p2}};
assign tmp2_fu_577_p2 = (tmp1_cast_reg_662 + tmp4_cast_fu_573_p1);
assign tmp3_fu_270_p2 = (ap_const_lv20_42000 - tmp1_cast_fu_266_p1);
assign tmp4_cast_fu_573_p1 = {{7{1'b0}}, {tmp4_fu_567_p2}};
assign tmp4_fu_567_p2 = i_cast_fu_564_p1 << ap_const_lv13_6;
assign tmp5_fu_599_p2 = (tmp8_cast_fu_595_p1 | ap_const_lv15_5000);
assign tmp6_fu_384_p2 = i_1_cast_fu_381_p1 << ap_const_lv13_6;
assign tmp7_cast_cast_fu_409_p1 = {{7{1'b0}}, {tmp7_fu_403_p2}};
assign tmp7_fu_403_p2 = (tmp6_fu_384_p2 + tmp_cast_fu_399_p1);
assign tmp8_cast_fu_595_p1 = {{8{1'b0}}, {tmp8_fu_589_p2}};
assign tmp8_fu_589_p2 = indvar1_cast_fu_586_p1 << ap_const_lv7_2;
assign tmp9_fu_609_p0 = {{7{tmp5_fu_599_p2[14]}}, {tmp5_fu_599_p2}};
assign tmp9_fu_609_p2 = (tmp9_fu_609_p0 + tmp2_cast_fu_582_p1);
assign tmp_10_fu_554_p2 = (j_mid2_reg_751 + ap_const_lv7_4);
assign tmp_12_fu_346_p1 = {{50{1'b0}}, {d_addr4_fu_340_p2}};
assign tmp_13_dup_fu_310_p2 = (i_1_phi_fu_150_p4 + ap_const_lv7_1);
assign tmp_13_fu_351_p2 = (j_1_mid2_reg_687 | ap_const_lv7_2);
assign tmp_14_fu_366_p1 = {{50{1'b0}}, {d_addr1_fu_360_p2}};
assign tmp_14_trn_cast_fu_327_p1 = {{7{1'b0}}, {j_1_mid2_reg_687}};
assign tmp_15_fu_444_p1 = {{64{1'b0}}, {p_0_fu_436_p3}};
assign tmp_16_trn_cast_fu_356_p1 = {{7{1'b0}}, {tmp_13_fu_351_p2}};
assign tmp_17_fu_449_p1 = {{46{tmp_16_reg_721[17]}}, {tmp_16_reg_721}};
assign tmp_18_fu_371_p2 = (j_1_mid2_reg_687 + ap_const_lv7_4);
assign tmp_1_fu_232_p2 = (counter < ap_const_lv7_43? 1'b1: 1'b0);
assign tmp_2_fu_238_p2 = (counter > ap_const_lv7_2? 1'b1: 1'b0);
assign tmp_3_fu_250_p2 = (tag == ap_const_lv2_0? 1'b1: 1'b0);
assign tmp_4_trn7_cast_fu_507_p1 = {{6{1'b0}}, {i_mid2_reg_758}};
assign tmp_5_fu_529_p1 = {{50{1'b0}}, {d_addr9_fu_523_p2}};
assign tmp_5_trn2_cast_fu_324_p1 = {{6{1'b0}}, {i_1_mid2_reg_694}};
assign tmp_6_dup_fu_493_p2 = (i_phi_fu_194_p4 + ap_const_lv7_1);
assign tmp_6_fu_549_p1 = {{50{1'b0}}, {d_addr6_fu_543_p2}};
assign tmp_7_trn_cast_fu_510_p1 = {{7{1'b0}}, {j_mid2_reg_751}};
assign tmp_8_fu_534_p2 = (j_mid2_reg_751 | ap_const_lv7_2);
assign tmp_9_fu_646_p1 = {{44{tmp_7_reg_785[19]}}, {tmp_7_reg_785}};
assign tmp_9_trn_cast_fu_539_p1 = {{7{1'b0}}, {tmp_8_fu_534_p2}};
assign tmp_cast_fu_399_p1 = {{6{1'b0}}, {tmp_fu_393_p2}};
assign tmp_fu_393_p2 = indvar_cast_fu_390_p1 << ap_const_lv7_2;
assign tmp_s_fu_641_p1 = {{64{1'b0}}, {p_s_fu_633_p3}};
always @ (ap_clk)
begin
    tmp1_cast_reg_662[0] <= 1'b0;
    tmp1_cast_reg_662[1] <= 1'b0;
    tmp1_cast_reg_662[2] <= 1'b0;
    tmp1_cast_reg_662[3] <= 1'b0;
    tmp1_cast_reg_662[4] <= 1'b0;
    tmp1_cast_reg_662[5] <= 1'b0;
    tmp1_cast_reg_662[6] <= 1'b0;
    tmp1_cast_reg_662[7] <= 1'b0;
    tmp1_cast_reg_662[8] <= 1'b0;
    tmp1_cast_reg_662[9] <= 1'b0;
    tmp1_cast_reg_662[10] <= 1'b0;
    tmp1_cast_reg_662[11] <= 1'b0;
    tmp1_cast_reg_662[19] <= 1'b0;
end

always @ (ap_clk)
begin
    tmp3_reg_667[0] <= 1'b0;
    tmp3_reg_667[1] <= 1'b0;
    tmp3_reg_667[2] <= 1'b0;
    tmp3_reg_667[3] <= 1'b0;
    tmp3_reg_667[4] <= 1'b0;
    tmp3_reg_667[5] <= 1'b0;
    tmp3_reg_667[6] <= 1'b0;
    tmp3_reg_667[7] <= 1'b0;
    tmp3_reg_667[8] <= 1'b0;
    tmp3_reg_667[9] <= 1'b0;
    tmp3_reg_667[10] <= 1'b0;
    tmp3_reg_667[11] <= 1'b0;
end



endmodule //write_r

