#!/usr/bin/env bash

if [ $# -ne 3 ]; then

	echo "usage: gather_all_sources <list-of-successful-designs> <path-to-ooc-directory> <remote-host>"
	exit -1
fi

LIST=$1
WORKDIR=$2
REMOTE=$3

# consider each design
designs=`cat $LIST`
for design in $designs; do

	# build directory variables
	localDir="${WORKDIR}${design}"
	extractedPath="${localDir}/icestorm/${design#"ooc_"}_extracted.v"
	echo "extracted netlist: ${extractedPath}"

	# grab the tech-mapped netlist
	techPath="${localDir}/build/${design}_Implmnt/${design}.vm"
	echo "looking for tech-mapped netlist: ${techPath}"
	remoteDir="research/a4/${design}"
	echo "making directory: ${remoteDir}"

	# make the landing zone
	ssh ${REMOTE} mkdir -p $remoteDir
	
	# do the deed
	scp $extractedPath $techPath "${REMOTE}:${remoteDir}"

done
