#! /usr/bin/env bash

numArgs=7

if [ "$#" -ne $numArgs ]; then
	
	echo "Usage: bitstream rtl constraints lse tcl wkdir dofile"
	exit
fi

# capture arguments
bitstream=$1 # bitstream in question
rtl=$2 # RTL code in question
constraints=$3 # design constraints file
lse=$4 # iCEcube2 project settings
tcl=$5 # iCEcube2 project flow
dofile=$6 # file for conformal comparison
wkdir=$7 # where the user wants the results

# create subdirectory for results
mkdir $wkdir

# store name of golden netlist
filename=$(basename -- "$rtl")
golden="${filename%.*}"
golden="${golden}_prim.v"

# move rtl into place
mkdir "${wkdir}/rtl"
mv $rtl "${wkdir}/rtl/"
rtl="rtl/${rtl}"

# move bitstream into place
icedir='icestorm'
mkdir "${wkdir}/${icedir}"
mv $bitstream "${wkdir}/${icedir}/"
bitstream="${icedir}/${bitstream}"

# move project project file and tcl flow into place
mv $lse $tcl $constraints $dofile $wkdir

# run iCEcube2 flow
cd $wkdir
lse -f $lse
tclsh $tcl

# unset LD_LIBRARY_PATH ...ugh
unset LD_LIBRARY_PATH

# unpack bitstream
asciiRep="${icedir}/unpacked_bitstream.asc"
iceunpack $bitstream > $asciiRep

# extract netlist
netlist="${icedir}/verilog_netlist.v"
icebox_vlog -p $constraints -s $asciiRep > $netlist

# move files to caedm
location="research/automation"
scp $dofile "caedm:~/${location}"
scp $netlist "caedm:~/${location}"
scp $golden "caedm:~/${location}"

# run the comparison
comparison="comparison.log"
ssh caedm "source .system && cd ${location} && lec -Dofile ${dofile} -LOGfile ${comparison} -NOGui" &> $comparison # this needs to change ...ugh

# look for the word "Equivalent"
result=$(tail -3 $comparison) 
if [[ $result == *"Equivalent"* ]]; then
	echo equivalent
else
	echo "not equivalent"
fi



