///////////////////////////////////////////////////////////////////////////////
//  Copyright (c) 1995/2015 Xilinx, Inc.
//  All Right Reserved.
///////////////////////////////////////////////////////////////////////////////
//
//   ____   ___
//  /   /\/   / 
// /___/  \  /     Vendor      : Xilinx 
// \   \   \/      Version     : 2015.4
//  \   \          Description : Xilinx Formal Library Component
//  /   /                        
// /___/   /\      Filename    : ILKN.v
// \   \  /  \ 
//  \___\/\___\                    
//                                 
///////////////////////////////////////////////////////////////////////////////
//  Revision:
//
//  End Revision:
///////////////////////////////////////////////////////////////////////////////

`timescale 1 ps / 1 ps 

`celldefine

module ILKN #(
  `ifdef XIL_TIMING //Simprim 
  parameter LOC = "UNPLACED",  
  `endif
  parameter BYPASS = "FALSE",
  parameter [1:0] CTL_RX_BURSTMAX = 2'h3,
  parameter [1:0] CTL_RX_CHAN_EXT = 2'h0,
  parameter [3:0] CTL_RX_LAST_LANE = 4'hB,
  parameter [15:0] CTL_RX_MFRAMELEN_MINUS1 = 16'h07FF,
  parameter CTL_RX_PACKET_MODE = "TRUE",
  parameter [2:0] CTL_RX_RETRANS_MULT = 3'h0,
  parameter [3:0] CTL_RX_RETRANS_RETRY = 4'h2,
  parameter [15:0] CTL_RX_RETRANS_TIMER1 = 16'h0000,
  parameter [15:0] CTL_RX_RETRANS_TIMER2 = 16'h0008,
  parameter [11:0] CTL_RX_RETRANS_WDOG = 12'h000,
  parameter [7:0] CTL_RX_RETRANS_WRAP_TIMER = 8'h00,
  parameter CTL_TEST_MODE_PIN_CHAR = "FALSE",
  parameter [1:0] CTL_TX_BURSTMAX = 2'h3,
  parameter [2:0] CTL_TX_BURSTSHORT = 3'h1,
  parameter [1:0] CTL_TX_CHAN_EXT = 2'h0,
  parameter CTL_TX_DISABLE_SKIPWORD = "TRUE",
  parameter [6:0] CTL_TX_FC_CALLEN = 7'h00,
  parameter [3:0] CTL_TX_LAST_LANE = 4'hB,
  parameter [15:0] CTL_TX_MFRAMELEN_MINUS1 = 16'h07FF,
  parameter [13:0] CTL_TX_RETRANS_DEPTH = 14'h0800,
  parameter [2:0] CTL_TX_RETRANS_MULT = 3'h0,
  parameter [1:0] CTL_TX_RETRANS_RAM_BANKS = 2'h3,
  parameter MODE = "TRUE",
  parameter SIM_VERSION = "2.0",
  parameter TEST_MODE_PIN_CHAR = "FALSE"
)(
  output [15:0] DRP_DO,
  output DRP_RDY,
  output [65:0] RX_BYPASS_DATAOUT00,
  output [65:0] RX_BYPASS_DATAOUT01,
  output [65:0] RX_BYPASS_DATAOUT02,
  output [65:0] RX_BYPASS_DATAOUT03,
  output [65:0] RX_BYPASS_DATAOUT04,
  output [65:0] RX_BYPASS_DATAOUT05,
  output [65:0] RX_BYPASS_DATAOUT06,
  output [65:0] RX_BYPASS_DATAOUT07,
  output [65:0] RX_BYPASS_DATAOUT08,
  output [65:0] RX_BYPASS_DATAOUT09,
  output [65:0] RX_BYPASS_DATAOUT10,
  output [65:0] RX_BYPASS_DATAOUT11,
  output [11:0] RX_BYPASS_ENAOUT,
  output [11:0] RX_BYPASS_IS_AVAILOUT,
  output [11:0] RX_BYPASS_IS_BADLYFRAMEDOUT,
  output [11:0] RX_BYPASS_IS_OVERFLOWOUT,
  output [11:0] RX_BYPASS_IS_SYNCEDOUT,
  output [11:0] RX_BYPASS_IS_SYNCWORDOUT,
  output [10:0] RX_CHANOUT0,
  output [10:0] RX_CHANOUT1,
  output [10:0] RX_CHANOUT2,
  output [10:0] RX_CHANOUT3,
  output [127:0] RX_DATAOUT0,
  output [127:0] RX_DATAOUT1,
  output [127:0] RX_DATAOUT2,
  output [127:0] RX_DATAOUT3,
  output RX_ENAOUT0,
  output RX_ENAOUT1,
  output RX_ENAOUT2,
  output RX_ENAOUT3,
  output RX_EOPOUT0,
  output RX_EOPOUT1,
  output RX_EOPOUT2,
  output RX_EOPOUT3,
  output RX_ERROUT0,
  output RX_ERROUT1,
  output RX_ERROUT2,
  output RX_ERROUT3,
  output [3:0] RX_MTYOUT0,
  output [3:0] RX_MTYOUT1,
  output [3:0] RX_MTYOUT2,
  output [3:0] RX_MTYOUT3,
  output RX_OVFOUT,
  output RX_SOPOUT0,
  output RX_SOPOUT1,
  output RX_SOPOUT2,
  output RX_SOPOUT3,
  output STAT_RX_ALIGNED,
  output STAT_RX_ALIGNED_ERR,
  output [11:0] STAT_RX_BAD_TYPE_ERR,
  output STAT_RX_BURSTMAX_ERR,
  output STAT_RX_BURST_ERR,
  output STAT_RX_CRC24_ERR,
  output [11:0] STAT_RX_CRC32_ERR,
  output [11:0] STAT_RX_CRC32_VALID,
  output [11:0] STAT_RX_DESCRAM_ERR,
  output [11:0] STAT_RX_DIAGWORD_INTFSTAT,
  output [11:0] STAT_RX_DIAGWORD_LANESTAT,
  output [255:0] STAT_RX_FC_STAT,
  output [11:0] STAT_RX_FRAMING_ERR,
  output STAT_RX_MEOP_ERR,
  output [11:0] STAT_RX_MF_ERR,
  output [11:0] STAT_RX_MF_LEN_ERR,
  output [11:0] STAT_RX_MF_REPEAT_ERR,
  output STAT_RX_MISALIGNED,
  output STAT_RX_MSOP_ERR,
  output [7:0] STAT_RX_MUBITS,
  output STAT_RX_MUBITS_UPDATED,
  output STAT_RX_OVERFLOW_ERR,
  output STAT_RX_RETRANS_CRC24_ERR,
  output STAT_RX_RETRANS_DISC,
  output [15:0] STAT_RX_RETRANS_LATENCY,
  output STAT_RX_RETRANS_REQ,
  output STAT_RX_RETRANS_RETRY_ERR,
  output [7:0] STAT_RX_RETRANS_SEQ,
  output STAT_RX_RETRANS_SEQ_UPDATED,
  output [2:0] STAT_RX_RETRANS_STATE,
  output [4:0] STAT_RX_RETRANS_SUBSEQ,
  output STAT_RX_RETRANS_WDOG_ERR,
  output STAT_RX_RETRANS_WRAP_ERR,
  output [11:0] STAT_RX_SYNCED,
  output [11:0] STAT_RX_SYNCED_ERR,
  output [11:0] STAT_RX_WORD_SYNC,
  output STAT_TX_BURST_ERR,
  output STAT_TX_ERRINJ_BITERR_DONE,
  output STAT_TX_OVERFLOW_ERR,
  output STAT_TX_RETRANS_BURST_ERR,
  output STAT_TX_RETRANS_BUSY,
  output STAT_TX_RETRANS_RAM_PERROUT,
  output [8:0] STAT_TX_RETRANS_RAM_RADDR,
  output STAT_TX_RETRANS_RAM_RD_B0,
  output STAT_TX_RETRANS_RAM_RD_B1,
  output STAT_TX_RETRANS_RAM_RD_B2,
  output STAT_TX_RETRANS_RAM_RD_B3,
  output [1:0] STAT_TX_RETRANS_RAM_RSEL,
  output [8:0] STAT_TX_RETRANS_RAM_WADDR,
  output [643:0] STAT_TX_RETRANS_RAM_WDATA,
  output STAT_TX_RETRANS_RAM_WE_B0,
  output STAT_TX_RETRANS_RAM_WE_B1,
  output STAT_TX_RETRANS_RAM_WE_B2,
  output STAT_TX_RETRANS_RAM_WE_B3,
  output STAT_TX_UNDERFLOW_ERR,
  output TX_OVFOUT,
  output TX_RDYOUT,
  output [63:0] TX_SERDES_DATA00,
  output [63:0] TX_SERDES_DATA01,
  output [63:0] TX_SERDES_DATA02,
  output [63:0] TX_SERDES_DATA03,
  output [63:0] TX_SERDES_DATA04,
  output [63:0] TX_SERDES_DATA05,
  output [63:0] TX_SERDES_DATA06,
  output [63:0] TX_SERDES_DATA07,
  output [63:0] TX_SERDES_DATA08,
  output [63:0] TX_SERDES_DATA09,
  output [63:0] TX_SERDES_DATA10,
  output [63:0] TX_SERDES_DATA11,

  input CORE_CLK,
  input CTL_RX_FORCE_RESYNC,
  input CTL_RX_RETRANS_ACK,
  input CTL_RX_RETRANS_ENABLE,
  input CTL_RX_RETRANS_ERRIN,
  input CTL_RX_RETRANS_FORCE_REQ,
  input CTL_RX_RETRANS_RESET,
  input CTL_RX_RETRANS_RESET_MODE,
  input CTL_TX_DIAGWORD_INTFSTAT,
  input [11:0] CTL_TX_DIAGWORD_LANESTAT,
  input CTL_TX_ENABLE,
  input CTL_TX_ERRINJ_BITERR_GO,
  input [3:0] CTL_TX_ERRINJ_BITERR_LANE,
  input [255:0] CTL_TX_FC_STAT,
  input [7:0] CTL_TX_MUBITS,
  input CTL_TX_RETRANS_ENABLE,
  input CTL_TX_RETRANS_RAM_PERRIN,
  input [643:0] CTL_TX_RETRANS_RAM_RDATA,
  input CTL_TX_RETRANS_REQ,
  input CTL_TX_RETRANS_REQ_VALID,
  input [11:0] CTL_TX_RLIM_DELTA,
  input CTL_TX_RLIM_ENABLE,
  input [7:0] CTL_TX_RLIM_INTV,
  input [11:0] CTL_TX_RLIM_MAX,
  input [9:0] DRP_ADDR,
  input DRP_CLK,
  input [15:0] DRP_DI,
  input DRP_EN,
  input DRP_WE,
  input LBUS_CLK,
  input RX_BYPASS_FORCE_REALIGNIN,
  input RX_BYPASS_RDIN,
  input RX_RESET,
  input [11:0] RX_SERDES_CLK,
  input [63:0] RX_SERDES_DATA00,
  input [63:0] RX_SERDES_DATA01,
  input [63:0] RX_SERDES_DATA02,
  input [63:0] RX_SERDES_DATA03,
  input [63:0] RX_SERDES_DATA04,
  input [63:0] RX_SERDES_DATA05,
  input [63:0] RX_SERDES_DATA06,
  input [63:0] RX_SERDES_DATA07,
  input [63:0] RX_SERDES_DATA08,
  input [63:0] RX_SERDES_DATA09,
  input [63:0] RX_SERDES_DATA10,
  input [63:0] RX_SERDES_DATA11,
  input [11:0] RX_SERDES_RESET,
  input TX_BCTLIN0,
  input TX_BCTLIN1,
  input TX_BCTLIN2,
  input TX_BCTLIN3,
  input [11:0] TX_BYPASS_CTRLIN,
  input [63:0] TX_BYPASS_DATAIN00,
  input [63:0] TX_BYPASS_DATAIN01,
  input [63:0] TX_BYPASS_DATAIN02,
  input [63:0] TX_BYPASS_DATAIN03,
  input [63:0] TX_BYPASS_DATAIN04,
  input [63:0] TX_BYPASS_DATAIN05,
  input [63:0] TX_BYPASS_DATAIN06,
  input [63:0] TX_BYPASS_DATAIN07,
  input [63:0] TX_BYPASS_DATAIN08,
  input [63:0] TX_BYPASS_DATAIN09,
  input [63:0] TX_BYPASS_DATAIN10,
  input [63:0] TX_BYPASS_DATAIN11,
  input TX_BYPASS_ENAIN,
  input [7:0] TX_BYPASS_GEARBOX_SEQIN,
  input [3:0] TX_BYPASS_MFRAMER_STATEIN,
  input [10:0] TX_CHANIN0,
  input [10:0] TX_CHANIN1,
  input [10:0] TX_CHANIN2,
  input [10:0] TX_CHANIN3,
  input [127:0] TX_DATAIN0,
  input [127:0] TX_DATAIN1,
  input [127:0] TX_DATAIN2,
  input [127:0] TX_DATAIN3,
  input TX_ENAIN0,
  input TX_ENAIN1,
  input TX_ENAIN2,
  input TX_ENAIN3,
  input TX_EOPIN0,
  input TX_EOPIN1,
  input TX_EOPIN2,
  input TX_EOPIN3,
  input TX_ERRIN0,
  input TX_ERRIN1,
  input TX_ERRIN2,
  input TX_ERRIN3,
  input [3:0] TX_MTYIN0,
  input [3:0] TX_MTYIN1,
  input [3:0] TX_MTYIN2,
  input [3:0] TX_MTYIN3,
  input TX_RESET,
  input TX_SERDES_REFCLK,
  input TX_SERDES_REFCLK_RESET,
  input TX_SOPIN0,
  input TX_SOPIN1,
  input TX_SOPIN2,
  input TX_SOPIN3
);

endmodule

`endcelldefine
