#!/usr/bin/env bash

if [ $# != 2 ]; then
	echo "usage: gendo <path-to-design-targets> <path-to-python-script>"
	exit
fi

WKDIR=$1
GENDOPATH=$2

for f in $(ls $WKDIR); do

	path="${WKDIR}/${f}"
	filePath="${path}/dofile.do"

	if [ -f "$filePath" ]; then
		
		rm $filePath
	fi

	echo "executing: python ${GENDOPATH} ${path}"

	python $GENDOPATH $path

done
