#!/usr/bin/env bash

if [ $# != 2 ]; then
	echo "usage: rundo <path-to-targets> <name-of-dofiles>"
	exit
fi

WKDIR=$1
DOFIL=$2

for d in $(ls $WKDIR); do

	# build logfile path
	logpath="${WKDIR}/${d}/${DOFIL}.log"

	# delete log file if it exists
	if [ -f "$logpath" ]; then rm $logpath 
	fi

	# build dofile path
	dopath="${WKDIR}/${d}/${DOFIL}.do"

	# do the deed
	lec -xl -nog -do $dopath -log $logpath

done
