import bfasst.compare_waveforms.file_generation
import bfasst.compare_waveforms.file_parsing
import bfasst.compare_waveforms.interface
import bfasst.compare_waveforms.templates
import bfasst.compare_waveforms.tools
