"Generate stubs for JAVA/RapidWright and BFASST dynamic imports."

from argparse import ArgumentParser
from pathlib import Path


def extract_keys(env_dir: Path) -> set[str]:
    """Scans all .env files in the given directory and returns a set of unique keys."""
    keys = set()
    # Parse all .env files
    for env_file in env_dir.glob("*.env"):
        with open(env_file, "r", encoding="utf-8") as f:
            lines = (l for l in (l.strip() for l in f) if l and not l.startswith("#") and "=" in l)
            _ = [keys.add(line.split("=", 1)[0].strip()) for line in lines]
    return sorted(keys)


def generate_stubs(keys: set[str], output_dir: Path):
    """Generates the bfasst stub files from environment."""
    content_header = [
        "# Autogenerated stub file for config module. Do not edit manually.\n\n",
        "from typing import TYPE_CHECKING\n",
    ]
    content = ((f"    {key}: str=''\n", f"    {key}: Path=Path()\n") for key in keys)
    with open(output_dir / "config_stubs.py", "w", encoding="utf-8") as f, open(
        output_dir / "paths_stubs.py", "w", encoding="utf-8"
    ) as p:
        f.writelines(content_header)
        p.writelines(content_header)
        p.write("from pathlib import Path\n")
        f.write("\nif TYPE_CHECKING:\n")
        p.write("\nif TYPE_CHECKING:\n")
        _ = [(f.write(line[0]), p.write(line[1])) for line in content]
        f.write("\n")
        p.write("\n")
    print(f"Generated: {output_dir / 'config_stubs.py'} and {output_dir / 'paths_stubs.py'}")


def bfasst_stubs(output_dir: Path):
    # Configuration
    base_dir = Path.cwd()
    env_dir = base_dir / "setup" / "env"

    keys = extract_keys(env_dir)
    if not keys:
        print("No keys found. Exiting.")
        return

    generate_stubs(keys, output_dir)


if __name__ == "__main__":
    parser = ArgumentParser(description="Generate Java stubs for RapidWright and its dependencies.")
    parser.add_argument("outputDir", type=str, help="Output directory for the generated stubs.")
    parser.add_argument("--java", action="store_true", help="Generate stubs for Java/Rapidwright")
    parser.add_argument(
        "--bfasst", action="store_true", help="Generate stubs for BFASST Env variables"
    )
    args = parser.parse_args()

    if args.java:
        import stubgenj

        import rapidwright as _
        import com.xilinx.rapidwright
        import java

        stubgenj.generateJavaStubs(
            [java, com.xilinx.rapidwright],
            outputDir=args.outputDir,
            includeJavadoc=False,
            useStubsSuffix=False,
        )

    if args.bfasst:
        bfasst_stubs(Path(args.outputDir))
