#! /usr/bin/env bash

rtl=$1

designName=$(basename -- "$rtl")
designName="${designName%.*}"
mkdir $designName

# move rtl into place
mkdir "${designName}/rtl"
mv $rtl "${designName}/rtl/"

lse="${designName}_lse.prj"

# make project settings file
iCEcube2="iCEcube2"
edifPath="$iCEcube2/$designName.edf"
projectLogPath="$iCEcube2/$designName.log"
rtl="rtl/${rtl}"
sed "s:<RTL>:${rtl}:; s:<EDIF>:${edifPath}:; s:<LOG>:${projectLogPath}:" template.prj > $lse

mv $lse $designName

